-- AlterTable
ALTER TABLE "items" ADD COLUMN     "details" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "priceCopper" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "priceGold" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "priceSilver" INTEGER NOT NULL DEFAULT 0;
