import type { Spell } from '../types.js';

/**
 * Truques do PHB 2014 (26). Ordem alfabética pelo nome em português.
 * Alcances em metros (60 pés = 18 m, 120 pés = 36 m...).
 */
export const CANTRIPS: readonly Spell[] = [
  {
    id: 'acid-splash',
    namePt: 'Salpico Ácido',
    nameEn: 'Acid Splash',
    level: 0,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você arremessa uma bolha de ácido. Escolha uma criatura a até 18 m, ou duas criaturas a até 18 m que estejam a 1,5 m uma da outra. Cada alvo faz uma salvaguarda de Destreza; se falhar, sofre 1d6 de dano de ácido.',
    save: 'dexterity',
    damage: [{ count: 1, sides: 6, bonus: 0, type: 'Ácido' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'blade-ward',
    namePt: 'Proteção contra Lâminas',
    nameEn: 'Blade Ward',
    level: 0,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Você traça um signo de proteção no ar. Até o fim do seu próximo turno, você tem resistência a dano contundente, perfurante e cortante causado por ataques com arma.',
    classes: [],
  },
  {
    id: 'chill-touch',
    namePt: 'Toque Arrepiante',
    nameEn: 'Chill Touch',
    level: 0,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Você cria uma mão espectral que ataca uma criatura a até 36 m. Faça um ataque de magia à distância: se acertar, o alvo sofre 1d8 de dano necrótico e não pode recuperar pontos de vida até o início do seu próximo turno. Se o alvo for um morto-vivo, ele também tem desvantagem nos ataques contra você até o fim do seu próximo turno.',
    attack: 'ranged',
    damage: [{ count: 1, sides: 8, bonus: 0, type: 'Necrótico' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'dancing-lights',
    namePt: 'Luzes Dançantes',
    nameEn: 'Dancing Lights',
    level: 0,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pouco de fósforo ou madeira luminescente' },
    componentsText: 'V, S, M (um pouco de fósforo ou madeira luminescente)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você cria até quatro luzes do tamanho de tochas dentro do alcance, que podem parecer tochas, lanternas ou orbes flutuantes. Como ação bônus, você move as luzes até 18 m para um ponto dentro do alcance.',
    classes: [],
  },
  {
    id: 'druidcraft',
    namePt: 'Truque Druídico',
    nameEn: 'Druidcraft',
    level: 0,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você cria pequenos efeitos ligados à natureza: prevê o tempo por 24 h, faz uma flor desabrochar, cria um efeito sensorial inofensivo ou acende/apaga uma vela, tocha ou fogueira pequena.',
    classes: [],
  },
  {
    id: 'eldritch-blast',
    namePt: 'Rajada Mística',
    nameEn: 'Eldritch Blast',
    level: 0,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Um feixe de energia crepitante atinge uma criatura a até 36 m. Faça um ataque de magia à distância: se acertar, o alvo sofre 1d10 de dano de força. Um raio novo é criado nos níveis 5, 11 e 17 — cada raio pode mirar o mesmo alvo ou outro.',
    attack: 'ranged',
    damage: [{ count: 1, sides: 10, bonus: 0, type: 'Força' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'fire-bolt',
    namePt: 'Raio de Fogo',
    nameEn: 'Fire Bolt',
    level: 0,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você arremessa um globo de fogo contra uma criatura ou objeto a até 36 m. Faça um ataque de magia à distância: se acertar, o alvo sofre 1d10 de dano de fogo. Objetos inflamáveis que não estejam sendo vestidos acendem.',
    attack: 'ranged',
    damage: [{ count: 1, sides: 10, bonus: 0, type: 'Fogo' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'friends',
    namePt: 'Amizade',
    nameEn: 'Friends',
    level: 0,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: false, somatic: true, material: true },
    material: { text: 'uma pequena quantidade de maquiagem' },
    componentsText: 'S, M (uma pequena quantidade de maquiagem)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você ganha vantagem em testes de Carisma contra uma criatura que não seja hostil. Quando a magia termina, a criatura percebe que foi manipulada e fica hostil a você.',
    classes: [],
  },
  {
    id: 'guidance',
    namePt: 'Orientação',
    nameEn: 'Guidance',
    level: 0,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você toca uma criatura voluntária. Uma vez, antes da magia acabar, ela pode rolar 1d4 e somar ao resultado de um teste de atributo.',
    classes: [],
  },
  {
    id: 'light',
    namePt: 'Luz',
    nameEn: 'Light',
    level: 0,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: false, material: true },
    material: { text: 'um vaga-lume ou musgo fosforescente' },
    componentsText: 'V, M (um vaga-lume ou musgo fosforescente)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Você toca um objeto de até 3 m em qualquer dimensão. Enquanto durar, o objeto emite luz plena num raio de 6 m e penumbra por mais 6 m. A cor é escolhida por você. O objeto pode ser coberto para bloquear a luz.',
    classes: [],
  },
  {
    id: 'mage-hand',
    namePt: 'Mão Mágica',
    nameEn: 'Mage Hand',
    level: 0,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Uma mão espectral aparece num ponto à sua escolha a até 9 m. Ela pode manipular um objeto, abrir uma porta destrancada, guardar ou pegar um item de um recipiente aberto, ou derramar o conteúdo de um frasco. Pode carregar até 5 kg e não ataca.',
    classes: [],
  },
  {
    id: 'mending',
    namePt: 'Reparar',
    nameEn: 'Mending',
    level: 0,
    school: 'transmutation',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'dois ímãs' },
    componentsText: 'V, S, M (dois ímãs)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'A magia repara uma única quebra ou rasgo num objeto que você toca, como um elo de corrente, uma chave partida, um manto rasgado ou a membrana de um odre. O dano reparado não pode passar de 30 cm de diâmetro; a magia pode consertar fisicamente objetos mágicos, mas não devolve a magia a eles.',
    classes: [],
  },
  {
    id: 'message',
    namePt: 'Mensagem',
    nameEn: 'Message',
    level: 0,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de fio de cobre' },
    componentsText: 'V, S, M (um pedaço de fio de cobre)',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Você aponta para uma criatura a até 36 m e sussurra uma mensagem. O alvo (e só ele) a ouve e pode responder num sussurro que você ouve. A magia funciona através de objetos sólidos se você conhecer o alvo.',
    classes: [],
  },
  {
    id: 'minor-illusion',
    namePt: 'Ilusão Menor',
    nameEn: 'Minor Illusion',
    level: 0,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: false, somatic: true, material: true },
    material: { text: 'um pedaço de lã' },
    componentsText: 'S, M (um pedaço de lã)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Você cria um som ou a imagem de um objeto num cubo de 1,5 m dentro do alcance, por 1 minuto. A ilusão é apenas visual (não gera som, luz, cheiro nem temperatura) ou apenas sonora. Um teste de Investigação (INT) contra a CD da sua magia revela que é falsa.',
    classes: [],
  },
  {
    id: 'poison-spray',
    namePt: 'Jato de Veneno',
    nameEn: 'Poison Spray',
    level: 0,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você estende a mão para uma criatura a até 3 m. Uma nuvem de gás nocivo sai de você: o alvo faz uma salvaguarda de Constituição; se falhar, sofre 1d12 de dano de veneno.',
    save: 'constitution',
    damage: [{ count: 1, sides: 12, bonus: 0, type: 'Veneno' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'prestidigitation',
    namePt: 'Prestidigitação',
    nameEn: 'Prestidigitation',
    level: 0,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Até 1 hora',
    concentration: false,
    ritual: false,
    description:
      'Você cria um efeito sensorial inofensivo (faíscas, aroma, som fraco), acende ou apaga uma vela/tocheira, limpa ou suja um objeto pequeno, aquece/resfria ou dá sabor a 30 cm³ de material, ou cria uma marca/objeto de ilusão que cabe na sua mão, por até 1 hora.',
    classes: [],
  },
  {
    id: 'produce-flame',
    namePt: 'Produzir Chama',
    nameEn: 'Produce Flame',
    level: 0,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '10 minutos',
    concentration: false,
    ritual: false,
    description:
      'Uma chama brota na sua mão, iluminando 3 m de luz plena e 3 m de penumbra. Enquanto durar, você pode arremessá-la: faça um ataque de magia à distância contra uma criatura a até 9 m; se acertar, sofre 1d8 de dano de fogo.',
    attack: 'ranged',
    damage: [{ count: 1, sides: 8, bonus: 0, type: 'Fogo' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'ray-of-frost',
    namePt: 'Raio de Gelo',
    nameEn: 'Ray of Frost',
    level: 0,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Um feixe de luz azulada e fria atinge uma criatura a até 18 m. Faça um ataque de magia à distância: se acertar, o alvo sofre 1d8 de dano de frio e o deslocamento dele cai 3 m até o início do seu próximo turno.',
    attack: 'ranged',
    damage: [{ count: 1, sides: 8, bonus: 0, type: 'Frio' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'resistance',
    namePt: 'Resistência',
    nameEn: 'Resistance',
    level: 0,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma miniatura de um manto' },
    componentsText: 'V, S, M (uma miniatura de um manto)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você toca uma criatura voluntária. Uma vez, antes da magia acabar, ela pode rolar 1d4 e somar a uma salvaguarda à escolha dela.',
    classes: [],
  },
  {
    id: 'sacred-flame',
    namePt: 'Chama Sagrada',
    nameEn: 'Sacred Flame',
    level: 0,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma luz semelhante a uma chama desce sobre uma criatura a até 18 m. O alvo faz uma salvaguarda de Destreza; se falhar, sofre 1d8 de dano radiante. O alvo não se beneficia de cobertura contra esta magia.',
    save: 'dexterity',
    damage: [{ count: 1, sides: 8, bonus: 0, type: 'Radiante' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'shillelagh',
    namePt: 'Clava Mágica',
    nameEn: 'Shillelagh',
    level: 0,
    school: 'transmutation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'visco, trevo e um pedaço de madeira' },
    componentsText: 'V, S, M (visco, trevo e um pedaço de madeira)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Você imbui um porrete ou cajado de madeira. Até a magia acabar, você pode usar Sabedoria no lugar de Força nos ataques e o dado de dano da arma vira 1d8. A magia acaba se você conjurar de novo ou largar a arma.',
    classes: [],
  },
  {
    id: 'shocking-grasp',
    namePt: 'Toque Elétrico',
    nameEn: 'Shocking Grasp',
    level: 0,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma criatura e libera um choque. Faça um ataque de magia corpo a corpo: se acertar, o alvo sofre 1d8 de dano elétrico e não pode fazer reações até o início do próximo turno dele. Você tem vantagem no ataque se o alvo estiver vestindo armadura de metal.',
    attack: 'melee',
    damage: [{ count: 1, sides: 8, bonus: 0, type: 'Elétrico' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'spare-the-dying',
    namePt: 'Poupar os Moribundos',
    nameEn: 'Spare the Dying',
    level: 0,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma criatura viva com 0 pontos de vida. Ela fica estável.',
    classes: [],
  },
  {
    id: 'thaumaturgy',
    namePt: 'Taumaturgia',
    nameEn: 'Thaumaturgy',
    level: 0,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Até 1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Você manifesta um pequeno sinal de poder sobrenatural: a sua voz fica três vezes mais alta, chamas mudam de cor, tremores inofensivos, um som repentino, abrir/fechar portas e janelas destrancadas, ou alterar a aparência dos seus olhos.',
    classes: [],
  },
  {
    id: 'thorn-whip',
    namePt: 'Chicote de Espinhos',
    nameEn: 'Thorn Whip',
    level: 0,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'o caule de uma planta com espinhos' },
    componentsText: 'V, S, M (o caule de uma planta com espinhos)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você cria um chicote de vinhas espinhosas que ataca uma criatura a até 9 m. Faça um ataque de magia corpo a corpo: se acertar, o alvo sofre 1d6 de dano perfurante e, se for Grande ou menor, você o puxa até 3 m na sua direção.',
    attack: 'melee',
    damage: [{ count: 1, sides: 6, bonus: 0, type: 'Perfurante' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
  {
    id: 'true-strike',
    namePt: 'Golpe Certeiro',
    nameEn: 'True Strike',
    level: 0,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: false, somatic: true, material: false },
    componentsText: 'S',
    duration: 'Concentração, até 1 rodada',
    concentration: true,
    ritual: false,
    description:
      'Você aponta o dedo para um alvo a até 9 m. No seu próximo turno, você ganha vantagem na primeira rolagem de ataque contra ele, desde que a magia ainda esteja ativa.',
    classes: [],
  },
  {
    id: 'vicious-mockery',
    namePt: 'Zombaria Viciosa',
    nameEn: 'Vicious Mockery',
    level: 0,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você lança uma sequência de insultos a uma criatura a até 18 m. Se ela falhar numa salvaguarda de Sabedoria, sofre 1d4 de dano psíquico e tem desvantagem na próxima rolagem de ataque antes do fim do próximo turno dela.',
    save: 'wisdom',
    damage: [{ count: 1, sides: 4, bonus: 0, type: 'Psíquico' }],
    cantripScaling: [
      { atLevel: 5, extraDice: 1 },
      { atLevel: 11, extraDice: 2 },
      { atLevel: 17, extraDice: 3 },
    ],
    classes: [],
  },
];
