import type { Spell } from '../types.js';

/**
 * Magias de 5º nível do PHB 2014 (42). Ordem alfabética pelo nome em inglês.
 * `classes` fica VAZIO até o Prompt 6.2.
 */
export const LEVEL_5: readonly Spell[] = [
  {
    id: 'animate-objects',
    namePt: 'Animar Objetos',
    nameEn: 'Animate Objects',
    level: 5,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Objetos não mágicos ganham vida e obedecem às suas ordens. Escolha até dez objetos Pequenos ou menores, ou menos objetos maiores. Cada um ataca com um golpe de magia.',
    upcast: { note: 'O número de objetos aumenta em dois por nível de espaço acima do 5º.' },
    classes: [],
  },
  {
    id: 'antilife-shell',
    namePt: 'Concha Antivida',
    nameEn: 'Antilife Shell',
    level: 5,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'sphere', sizeMeters: 3, note: 'origem em você' },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma barreira impede que criaturas que não sejam constructos nem mortos-vivos entrem numa esfera de 3 m de raio centrada em você. A magia acaba se você se mover para forçar a passagem.',
    classes: [],
  },
  {
    id: 'awaken',
    namePt: 'Despertar',
    nameEn: 'Awaken',
    level: 5,
    school: 'transmutation',
    castingTime: '8 horas',
    castingTimeKind: 'hour',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma ágata no valor de 1000 PO, consumida' },
    componentsText: 'V, S, M (uma ágata no valor de 1000 PO, consumida)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma besta ou planta de INT 3 ou menos e a dota de inteligência (INT 10) e da capacidade de falar um idioma que você conheça. A criatura fica enfeitiçada por 30 dias.',
    classes: [],
  },
  {
    id: 'banishing-smite',
    namePt: 'Golpe Banidor',
    nameEn: 'Banishing Smite',
    level: 5,
    school: 'abjuration',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar com uma arma, o alvo sofre 5d10 de dano de força adicional e, se ficar com 50 PV ou menos, é banido para um semiplano inofensivo até a magia acabar.',
    damage: [{ count: 5, sides: 10, bonus: 0, type: 'Força' }],
    classes: [],
  },
  {
    id: 'bigbys-hand',
    namePt: 'Mão de Bigby',
    nameEn: "Bigby's Hand",
    level: 5,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma casca de ovo e uma luva' },
    componentsText: 'V, S, M (uma casca de ovo e uma luva)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma mão de força Grande aparece. Com uma ação bônus, você pode movê-la até 18 m e usar um efeito: punho cerrado (4d8 de força), mão prensora (salvaguarda de Destreza ou impedido) ou mão empurradora.',
    attack: 'melee',
    damage: [{ count: 4, sides: 8, bonus: 0, type: 'Força' }],
    upcast: { note: 'O dano do punho aumenta 2d8 por nível de espaço acima do 5º.' },
    classes: [],
  },
  {
    id: 'circle-of-power',
    namePt: 'Círculo de Poder',
    nameEn: 'Circle of Power',
    level: 5,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma energia divina irradia de você. Criaturas amigáveis a até 9 m têm vantagem em salvaguardas contra magias e, quando passam numa salvaguarda que causaria metade do dano, não sofrem dano nenhum.',
    classes: [],
  },
  {
    id: 'cloudkill',
    namePt: 'Nuvem Mortal',
    nameEn: 'Cloudkill',
    level: 5,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma nuvem venenosa de 6 m de raio surge. Cada criatura na área faz salvaguarda de Constituição ou sofre 5d8 de dano de veneno (metade se passar); a nuvem se afasta 3 m de você a cada turno.',
    save: 'constitution',
    damage: [{ count: 5, sides: 8, bonus: 0, type: 'Veneno' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'commune',
    namePt: 'Comunhão',
    nameEn: 'Commune',
    level: 5,
    school: 'divination',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'incenso e água benta' },
    componentsText: 'V, S, M (incenso e água benta)',
    duration: '1 minuto',
    concentration: false,
    ritual: true,
    description:
      'Você faz até três perguntas de sim ou não a uma entidade divina e recebe respostas verídicas, embora possam ser de uma palavra.',
    classes: [],
  },
  {
    id: 'commune-with-nature',
    namePt: 'Comunhão com a Natureza',
    nameEn: 'Commune with Nature',
    level: 5,
    school: 'divination',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    description:
      'Você conhece brevemente a terra ao redor: até três fatos sobre o terreno, corpos d’água, plantas, minerais, bestas ou povos num raio de 4,5 km.',
    classes: [],
  },
  {
    id: 'cone-of-cold',
    namePt: 'Cone de Frio',
    nameEn: 'Cone of Cold',
    level: 5,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'cone', sizeMeters: 18 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pequeno cone de cristal ou vidro' },
    componentsText: 'V, S, M (um pequeno cone de cristal ou vidro)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma explosão de ar gelado sai de você num cone de 18 m. Cada criatura na área faz salvaguarda de Constituição ou sofre 8d8 de dano de frio (metade se passar).',
    save: 'constitution',
    damage: [{ count: 8, sides: 8, bonus: 0, type: 'Frio' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'conjure-elemental',
    namePt: 'Convocar Elemental',
    nameEn: 'Conjure Elemental',
    level: 5,
    school: 'conjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'incenso aceso para o ar, argila mole para a terra, água para a água e areia para o fogo' },
    componentsText: 'V, S, M (incenso, argila, água e areia)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Um elemental de NC 5 ou menos surge num espaço desocupado e obedece às suas ordens. Se você perder a concentração, o elemental fica hostil a você.',
    upcast: { note: 'O NC máximo aumenta em 1 por nível de espaço acima do 5º.' },
    classes: [],
  },
  {
    id: 'conjure-volley',
    namePt: 'Salva de Conjuração',
    nameEn: 'Conjure Volley',
    level: 5,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'cylinder', sizeMeters: 12, note: 'raio de 12 m' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma munição ou arma de arremesso' },
    componentsText: 'V, S, M (uma munição ou arma de arremesso)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você faz chover cópias de uma arma sobre um cilindro de 12 m de raio. Cada criatura na área faz salvaguarda de Destreza ou sofre 8d8 de dano do tipo da arma (metade se passar).',
    save: 'dexterity',
    damage: [{ count: 8, sides: 8, bonus: 0, type: null }],
    classes: [],
  },
  {
    id: 'contact-other-plane',
    namePt: 'Contato Extraplanar',
    nameEn: 'Contact Other Plane',
    level: 5,
    school: 'divination',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: '1 minuto',
    concentration: false,
    ritual: true,
    description:
      'Você contata uma entidade de outro plano e faz até cinco perguntas de uma palavra. Faz salvaguarda de Inteligência (CD 15) ou sofre 6d6 de dano psíquico e fica insano até um descanso longo.',
    save: 'intelligence',
    classes: [],
  },
  {
    id: 'contagion',
    namePt: 'Contágio',
    nameEn: 'Contagion',
    level: 5,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '7 dias',
    concentration: false,
    ritual: false,
    description:
      'Faça um ataque de magia corpo a corpo. Se acertar, o alvo fica doente (desvantagem em testes e atributos) e, se falhar em três salvaguardas de Constituição, contrai uma doença grave escolhida por você.',
    save: 'constitution',
    classes: [],
  },
  {
    id: 'creation',
    namePt: 'Criação',
    nameEn: 'Creation',
    level: 5,
    school: 'illusion',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço da matéria do tipo a criar' },
    componentsText: 'V, S, M (um pedaço da matéria do tipo a criar)',
    duration: 'Especial',
    concentration: false,
    ritual: false,
    description:
      'Você cria um objeto de matéria vegetal, mineral ou de tecido. Sua permanência depende do material (de 1 dia para vegetal a permanente para pedra ou metais preciosos).',
    upcast: { note: 'Aumenta o tamanho do objeto por nível de espaço acima do 5º.' },
    classes: [],
  },
  {
    id: 'destructive-wave',
    namePt: 'Onda Destrutiva',
    nameEn: 'Destructive Wave',
    level: 5,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'sphere', sizeMeters: 9, note: 'origem em você' },
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma onda de energia divina varre uma esfera de 9 m de raio centrada em você. Cada criatura à sua escolha na área faz salvaguarda de Constituição: se falhar, sofre 5d6 de dano de trovão e 5d6 de dano radiante ou necrótico (à sua escolha) e cai prostrada; se passar, metade e não cai.',
    save: 'constitution',
    damage: [
      { count: 5, sides: 6, bonus: 0, type: 'Trovão' },
      { count: 5, sides: 6, bonus: 0, type: 'Radiante' },
    ],
    classes: [],
  },
  {
    id: 'dispel-evil-and-good',
    namePt: 'Dissipar o Mal e o Bem',
    nameEn: 'Dispel Evil and Good',
    level: 5,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'água benta ou prata e ferro em pó' },
    componentsText: 'V, S, M (água benta ou prata e ferro em pó)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma energia protetora o cerca: aberrações, celestiais, corruptores, elementais, fadas, imundícies e mortos-vivos têm desvantagem nos ataques contra você. Você pode encerrar a magia para dissipar ou romper encantamentos e repelir tais criaturas.',
    classes: [],
  },
  {
    id: 'dominate-person',
    namePt: 'Dominar Pessoa',
    nameEn: 'Dominate Person',
    level: 5,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Um humanoide a até 18 m faz salvaguarda de Sabedoria ou fica enfeitiçado e sob seu controle; você pode usar uma ação para comandá-lo. Tem vantagem se estiver lutando com ele.',
    save: 'wisdom',
    upcast: { note: 'Com espaços de 6º/7º dura até 10 min; de 8º ou maior, até 1 hora.' },
    classes: [],
  },
  {
    id: 'dream',
    namePt: 'Sonho',
    nameEn: 'Dream',
    level: 5,
    school: 'illusion',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Especial',
    rangeKind: 'special',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um punhado de areia, um pouco de tinta e uma pena' },
    componentsText: 'V, S, M (areia, tinta e uma pena)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Você entra no sonho de uma criatura conhecida no mesmo plano. Você pode moldar o sonho como mensageiro; se fizer uma forma assustadora, o alvo não descansa e sofre 3d6 de dano psíquico.',
    save: 'wisdom',
    damage: [{ count: 3, sides: 6, bonus: 0, type: 'Psíquico' }],
    classes: [],
  },
  {
    id: 'flame-strike',
    namePt: 'Golpe Flamejante',
    nameEn: 'Flame Strike',
    level: 5,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'cylinder', sizeMeters: 3, note: 'raio de 3 m, 12 m de altura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de enxofre' },
    componentsText: 'V, S, M (uma pitada de enxofre)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma coluna de fogo divino desce num cilindro de 3 m de raio e 12 m de altura. Cada criatura na área faz salvaguarda de Destreza e sofre 4d6 de dano de fogo e 4d6 de dano radiante (metade se passar).',
    save: 'dexterity',
    damage: [
      { count: 4, sides: 6, bonus: 0, type: 'Fogo' },
      { count: 4, sides: 6, bonus: 0, type: 'Radiante' },
    ],
    upcast: { extraDicePerSlot: 1, note: 'Some 1d6 de fogo ou radiante por nível acima do 5º.' },
    classes: [],
  },
  {
    id: 'geas',
    namePt: 'Geas',
    nameEn: 'Geas',
    level: 5,
    school: 'enchantment',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: '30 dias',
    concentration: false,
    ritual: false,
    description:
      'Você impõe uma ordem mágica a uma criatura a até 18 m. Se ela desobedecer, sofre 5d10 de dano psíquico (no máximo uma vez por dia). Uma Remover Maldição, Restauração Maior ou Desejo a liberta.',
    save: 'wisdom',
    damage: [{ count: 5, sides: 10, bonus: 0, type: 'Psíquico' }],
    upcast: { note: 'Com espaço de 7º/8º dura 1 ano; de 9º, até ser dissipada.' },
    classes: [],
  },
  {
    id: 'greater-restoration',
    namePt: 'Restauração Maior',
    nameEn: 'Greater Restoration',
    level: 5,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pó de diamante no valor de 100 PO, consumido' },
    componentsText: 'V, S, M (pó de diamante no valor de 100 PO, consumido)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você remove um efeito debilitante de uma criatura: um nível de exaustão, um encantamento ou petrificação, uma maldição, ou reduz um atributo a 0 ou os PV máximos.',
    classes: [],
  },
  {
    id: 'hallow',
    namePt: 'Sacralizar',
    nameEn: 'Hallow',
    level: 5,
    school: 'evocation',
    castingTime: '24 horas',
    castingTimeKind: 'hour',
    range: 'Toque',
    rangeKind: 'touch',
    area: { shape: 'sphere', sizeMeters: 18 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'ervas, óleos e incenso no valor de 1000 PO, consumidos' },
    componentsText: 'V, S, M (ervas, óleos e incenso no valor de 1000 PO, consumidos)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: false,
    description:
      'Você imbui uma área de 18 m de raio com poder sagrado: criaturas escolhidas ficam abençoadas ou amaldiçoadas, celestiais/elementais/fadas/imundícias/mortos-vivos podem não entrar e você pode aplicar um efeito extra (luz do dia, silêncio, medo, etc.).',
    classes: [],
  },
  {
    id: 'hold-monster',
    namePt: 'Imobilizar Monstro',
    nameEn: 'Hold Monster',
    level: 5,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pequeno pedaço reto de ferro' },
    componentsText: 'V, S, M (um pequeno pedaço reto de ferro)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura a até 27 m (exceto mortos-vivos) faz salvaguarda de Sabedoria ou fica paralisada, repetindo a salvaguarda no fim de cada turno.',
    save: 'wisdom',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'insect-plague',
    namePt: 'Praga de Insetos',
    nameEn: 'Insect Plague',
    level: 5,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '90 m',
    rangeKind: 'ranged',
    rangeMeters: 90,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'a pata de um gafanhoto' },
    componentsText: 'V, S, M (a pata de um gafanhoto)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma nuvem de gafanhotos vorazes preenche uma esfera de 6 m de raio. Cada criatura que comece o turno na área faz salvaguarda de Constituição ou sofre 4d10 de dano perfurante (metade se passar); a área é de visão fortemente obscurecida.',
    save: 'constitution',
    damage: [{ count: 4, sides: 10, bonus: 0, type: 'Perfurante' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'legend-lore',
    namePt: 'Lenda',
    nameEn: 'Legend Lore',
    level: 5,
    school: 'divination',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'incenso no valor de 250 PO e tiras de marfim no valor de 50 PO, consumidos' },
    componentsText: 'V, S, M (incenso de 250 PO e marfim de 50 PO, consumidos)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você nomeia ou descreve uma pessoa, lugar ou objeto famoso e recebe relatos resumidos de sua história, mesmo que sejam lendas exageradas.',
    classes: [],
  },
  {
    id: 'mass-cure-wounds',
    namePt: 'Curar Ferimentos em Massa',
    nameEn: 'Mass Cure Wounds',
    level: 5,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'sphere', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Até seis criaturas numa esfera de 9 m de raio recuperam 3d8 + o seu modificador de atributo de conjuração em pontos de vida cada. Não afeta mortos-vivos nem constructos.',
    healing: { count: 3, sides: 8, bonus: 0, type: null },
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'mislead',
    namePt: 'Mistificar',
    nameEn: 'Mislead',
    level: 5,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: false, somatic: true, material: false },
    componentsText: 'S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você fica invisível e cria uma dupla ilusória sua no mesmo lugar. Com uma ação, você move a dupla até o dobro do seu deslocamento e pode ver através dos olhos dela como se estivesse lá.',
    classes: [],
  },
  {
    id: 'modify-memory',
    namePt: 'Modificar Memória',
    nameEn: 'Modify Memory',
    level: 5,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura a até 9 m faz salvaguarda de Sabedoria (com vantagem se você estiver lutando com ela) ou fica enfeitiçada. Você pode alterar a lembrança dela de um evento das últimas 24 h.',
    save: 'wisdom',
    upcast: { note: 'Com espaço de 6º ou superior, alcance eventos dos últimos 7 dias (8º: 30 dias; 9º: 1 ano).' },
    classes: [],
  },
  {
    id: 'passwall',
    namePt: 'Passagem',
    nameEn: 'Passwall',
    level: 5,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'sementes de gergelim' },
    componentsText: 'V, S, M (sementes de gergelim)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma passagem de 1,5 m de largura, 2,4 m de altura e até 6 m de profundidade se abre numa superfície de madeira, gesso ou pedra que você enxergue.',
    classes: [],
  },
  {
    id: 'planar-binding',
    namePt: 'Conjurar Seres Extraplanares',
    nameEn: 'Planar Binding',
    level: 5,
    school: 'abjuration',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma joia no valor de 1000 PO, consumida' },
    componentsText: 'V, S, M (uma joia no valor de 1000 PO, consumida)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Você tenta prender um celestial, elemental, corruptor ou fada a seu serviço. Se o alvo falhar na salvaguarda de Carisma, deve servi-lo pelo tempo da magia.',
    save: 'charisma',
    upcast: { note: 'A duração aumenta por nível de espaço acima do 5º (até 1 ano e 1 dia com 9º).' },
    classes: [],
  },
  {
    id: 'raise-dead',
    namePt: 'Ressuscitar',
    nameEn: 'Raise Dead',
    level: 5,
    school: 'necromancy',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um diamante no valor de 500 PO, consumido' },
    componentsText: 'V, S, M (um diamante no valor de 500 PO, consumido)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma criatura que morreu há até 10 dias e ela volta à vida com 1 PV. A magia neutraliza venenos e cura doenças que a mataram, mas não morte por velhice nem partes do corpo perdidas.',
    classes: [],
  },
  {
    id: 'rarys-telepathic-bond',
    namePt: 'Vínculo Telepático de Rary',
    nameEn: "Rary's Telepathic Bond",
    level: 5,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pedaços de casca de ovo de duas criaturas diferentes' },
    componentsText: 'V, S, M (pedaços de casca de ovo)',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    description:
      'Até oito criaturas voluntárias a até 9 m ficam mentalmente ligadas por 1 h, podendo se comunicar telepaticamente a qualquer distância (desde que no mesmo plano).',
    classes: [],
  },
  {
    id: 'reincarnate',
    namePt: 'Reencarnar',
    nameEn: 'Reincarnate',
    level: 5,
    school: 'transmutation',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'óleos e unguentos no valor de 1000 PO, consumidos' },
    componentsText: 'V, S, M (óleos e unguentos no valor de 1000 PO, consumidos)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma criatura morta há até 10 dias e ela reencarna num novo corpo adulto de uma raça aleatória (ou mantendo a sua, conforme a rolagem). Ela perde as lembranças da raça anterior.',
    classes: [],
  },
  {
    id: 'scrying',
    namePt: 'Vidência',
    nameEn: 'Scrying',
    level: 5,
    school: 'divination',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um foco no valor de 1000 PO (bola de cristal, espelho etc.)' },
    componentsText: 'V, S, M (um foco no valor de 1000 PO)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Você vê e ouve uma criatura à sua escolha no mesmo plano. O alvo faz salvaguarda de Sabedoria (com modificadores conforme o conhecimento que você tem dele); se falhar, pode ser observado por 10 min.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'seeming',
    namePt: 'Aparência',
    nameEn: 'Seeming',
    level: 5,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Você muda a aparência de cada criatura a até 9 m. Uma criatura involuntária faz salvaguarda de Carisma; um teste de Investigação contra a CD da magia revela a ilusão.',
    save: 'charisma',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'swift-quiver',
    namePt: 'Aljava Veloz',
    nameEn: 'Swift Quiver',
    level: 5,
    school: 'transmutation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma aljava com pelo menos uma munição' },
    componentsText: 'V, S, M (uma aljava com munição)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A aljava que você toca cria munição mágica. Enquanto durar, você pode usar uma ação bônus a cada turno para fazer dois ataques com uma arma que dispara munição da aljava.',
    classes: [],
  },
  {
    id: 'telekinesis',
    namePt: 'Telecinesia',
    nameEn: 'Telekinesis',
    level: 5,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Você move criaturas ou objetos com a mente. Uma criatura a até 18 m faz salvaguarda de Força ou é movida 9 m; um objeto pode ser movido até 9 m por turno.',
    save: 'strength',
    classes: [],
  },
  {
    id: 'teleportation-circle',
    namePt: 'Círculo de Teleporte',
    nameEn: 'Teleportation Circle',
    level: 5,
    school: 'conjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'gises e tintas raras no valor de 50 PO, consumidos' },
    componentsText: 'V, S, M (gises e tintas raras no valor de 50 PO, consumidos)',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Você abre um portal para outro círculo de teleporte permanente cuja sequência de selos você conheça, no mesmo plano. O portal dura até o fim do seu próximo turno.',
    classes: [],
  },
  {
    id: 'tree-stride',
    namePt: 'Passo de Árvore',
    nameEn: 'Tree Stride',
    level: 5,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma vez por turno, você pode usar 1,5 m de movimento para entrar numa árvore viva e se teleportar de dentro dela para outra árvore do mesmo tipo a até 150 m, saindo a 1,5 m do destino.',
    classes: [],
  },
  {
    id: 'wall-of-force',
    namePt: 'Muralha de Força',
    nameEn: 'Wall of Force',
    level: 5,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de pó de gema de cristal' },
    componentsText: 'V, S, M (uma pitada de pó de gema de cristal)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma parede invisível de força surge: hemisfério de até 3 m de raio, esfera plana ou painéis de 3 m × 3 m. Nada pode atravessá-la fisicamente e ela é imune a quase todas as magias.',
    classes: [],
  },
  {
    id: 'wall-of-stone',
    namePt: 'Muralha de Pedra',
    nameEn: 'Wall of Stone',
    level: 5,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pequeno bloco de granito' },
    componentsText: 'V, S, M (um pequeno bloco de granito)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma parede de pedra não mágica surge a partir de uma superfície de pedra. São dez painéis de 3 m × 3 m (podendo virar uma rampa ou se estender); vira permanente se mantiver a concentração por 10 min.',
    classes: [],
  },
];
