import type { Spell } from '../types.js';

/**
 * Magias de 2º nível do PHB 2014 (59). Ordem alfabética pelo nome em inglês.
 * `classes` fica VAZIO até o Prompt 6.2.
 */
export const LEVEL_2: readonly Spell[] = [
  {
    id: 'aid',
    namePt: 'Ajuda',
    nameEn: 'Aid',
    level: 2,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma tira de tecido branco' },
    componentsText: 'V, S, M (uma tira de tecido branco)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Até três criaturas à sua escolha a até 9 m têm os PV máximos e atuais aumentados em 5 por 8 h.',
    upcast: { note: 'O bônus de PV aumenta em 5 por nível de espaço acima do 2º.' },
    classes: [],
  },
  {
    id: 'alter-self',
    namePt: 'Alterar-se',
    nameEn: 'Alter Self',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você assume uma forma diferente: adaptar-se ao ambiente (respirar na água, nadar), mudar a aparência, ou ganhar armas naturais (1d6 + FOR).',
    classes: [],
  },
  {
    id: 'animal-messenger',
    namePt: 'Mensageiro Animal',
    nameEn: 'Animal Messenger',
    level: 2,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de comida' },
    componentsText: 'V, S, M (um pedaço de comida)',
    duration: '24 horas',
    concentration: false,
    ritual: true,
    description:
      'Uma besta Minúscula a até 9 m faz salvaguarda de Carisma ou fica enfeitiçada e tenta entregar uma mensagem sua a um destino que você descreva, viajando pela rota que você conheça.',
    save: 'charisma',
    upcast: { note: 'A duração aumenta por nível de espaço acima do 2º.' },
    classes: [],
  },
  {
    id: 'arcane-lock',
    namePt: 'Tranca Arcana',
    nameEn: 'Arcane Lock',
    level: 2,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pó de ouro no valor de 25 PO, consumido' },
    componentsText: 'V, S, M (pó de ouro no valor de 25 PO, consumido)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: false,
    description:
      'Uma porta, janela, portal ou recipiente fechado que você toca fica magicamente trancado, com CD para arrombar +10 por 8 h após cada conjuração.',
    classes: [],
  },
  {
    id: 'augury',
    namePt: 'Augúrio',
    nameEn: 'Augury',
    level: 2,
    school: 'divination',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'bastões, ossos ou runas marcadas, no valor de 25 PO' },
    componentsText: 'V, S, M (bastões, ossos ou runas marcadas, no valor de 25 PO)',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    description:
      'Você recebe um presságio sobre o resultado de um curso de ação planejado para os próximos 30 min: ventura, desgraça, ventura e desgraça, ou nada.',
    classes: [],
  },
  {
    id: 'barkskin',
    namePt: 'Pele de Árvore',
    nameEn: 'Barkskin',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um punhado de casca de carvalho' },
    componentsText: 'V, S, M (um punhado de casca de carvalho)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura voluntária que você toca tem a pele endurecida: a CA dela não pode ser inferior a 16 enquanto a magia durar.',
    classes: [],
  },
  {
    id: 'beast-sense',
    namePt: 'Sentido de Besta',
    nameEn: 'Beast Sense',
    level: 2,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: false, somatic: true, material: false },
    componentsText: 'S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: true,
    description:
      'Você toca uma besta voluntária e pode usar sua ação para ver através dos olhos dela e ouvir o que ela ouve enquanto a magia durar.',
    classes: [],
  },
  {
    id: 'blindness-deafness',
    namePt: 'Cegueira/Surdez',
    nameEn: 'Blindness/Deafness',
    level: 2,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura a até 9 m faz salvaguarda de Constituição ou fica cega ou surda (à sua escolha) por 1 minuto, repetindo a salvaguarda no fim de cada turno.',
    save: 'constitution',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'blur',
    namePt: 'Desfoque',
    nameEn: 'Blur',
    level: 2,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Seu corpo fica embaçado e tremeluzente. Enquanto durar, criaturas têm desvantagem nos ataques contra você (não vale se elas não dependem da visão).',
    classes: [],
  },
  {
    id: 'branding-smite',
    namePt: 'Golpe Marcante',
    nameEn: 'Branding Smite',
    level: 2,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar com uma arma, o alvo sofre 2d6 de dano radiante adicional e emite luz, não podendo ficar invisível até a magia acabar.',
    damage: [{ count: 2, sides: 6, bonus: 0, type: 'Radiante' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'calm-emotions',
    namePt: 'Acalmar Emoções',
    nameEn: 'Calm Emotions',
    level: 2,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Cada humanoide numa esfera de 6 m de raio a até 18 m faz salvaguarda de Carisma. Você pode suprimir efeitos de encantamento/medo ou tornar criaturas indiferentes a quem elas são hostis.',
    save: 'charisma',
    classes: [],
  },
  {
    id: 'cloud-of-daggers',
    namePt: 'Nuvem de Adagas',
    nameEn: 'Cloud of Daggers',
    level: 2,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'cube', sizeMeters: 1.5 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um caco de vidro' },
    componentsText: 'V, S, M (um caco de vidro)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você enche um cubo de 1,5 m de adagas giratórias. Uma criatura que entre na área ou comece o turno ali sofre 4d4 de dano cortante.',
    damage: [{ count: 4, sides: 4, bonus: 0, type: 'Cortante' }],
    upcast: { extraDicePerSlot: 2 },
    classes: [],
  },
  {
    id: 'continual-flame',
    namePt: 'Chama Contínua',
    nameEn: 'Continual Flame',
    level: 2,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pó de rubi no valor de 50 PO, consumido' },
    componentsText: 'V, S, M (pó de rubi no valor de 50 PO, consumido)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: false,
    description:
      'Uma chama brilhante, quente e sem fumaça surge de um objeto que você toca, emitindo luz como uma tocha. A chama pode ser coberta, mas não apagada.',
    classes: [],
  },
  {
    id: 'cordon-of-arrows',
    namePt: 'Cordão de Flechas',
    nameEn: 'Cordon of Arrows',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '1,5 m',
    rangeKind: 'ranged',
    rangeMeters: 1.5,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'quatro ou mais flechas ou virotes' },
    componentsText: 'V, S, M (quatro ou mais flechas ou virotes)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Você planta quatro munições no chão, protegendo uma área. Quando uma criatura se move a até 9 m do cordão, uma flecha dispara: ela faz salvaguarda de Destreza ou sofre 1d6 de dano perfurante.',
    save: 'dexterity',
    damage: [{ count: 1, sides: 6, bonus: 0, type: 'Perfurante' }],
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'crown-of-madness',
    namePt: 'Coroa da Loucura',
    nameEn: 'Crown of Madness',
    level: 2,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Um humanoide a até 36 m faz salvaguarda de Sabedoria ou fica enfeitiçado; antes de se mover a cada turno, deve usar a ação para atacar uma criatura que você escolher (exceto ele mesmo).',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'darkness',
    namePt: 'Escuridão',
    nameEn: 'Darkness',
    level: 2,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'sphere', sizeMeters: 4.5 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pelo de morcego e uma pitada de carvão' },
    componentsText: 'V, M (pelo de morcego e uma pitada de carvão)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Escuridão mágica preenche uma esfera de 4,5 m de raio. Visão no escuro não a penetra e luz não mágica não a ilumina.',
    classes: [],
  },
  {
    id: 'darkvision',
    namePt: 'Visão no Escuro',
    nameEn: 'Darkvision',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma cenoura seca ou uma ágata' },
    componentsText: 'V, S, M (uma cenoura seca ou uma ágata)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura voluntária que você toca ganha visão no escuro de até 18 m por 8 h.',
    classes: [],
  },
  {
    id: 'detect-thoughts',
    namePt: 'Detectar Pensamentos',
    nameEn: 'Detect Thoughts',
    level: 2,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma moeda de cobre' },
    componentsText: 'V, S, M (uma moeda de cobre)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você lê pensamentos superficiais de criaturas a até 9 m e, com uma ação, sonda a mente de uma criatura visível: ela faz salvaguarda de Sabedoria ou você descobre o que mais a preocupa.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'enhance-ability',
    namePt: 'Aprimorar Atributo',
    nameEn: 'Enhance Ability',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pelo ou pena de uma besta' },
    componentsText: 'V, S, M (pelo ou pena de uma besta)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura que você toca ganha vantagem em testes de um atributo escolhido e benefícios adicionais (ex.: Força: carga dobrada; Destreza: não sofre dano de queda de até 6 m).',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'enlarge-reduce',
    namePt: 'Ampliar/Reduzir',
    nameEn: 'Enlarge/Reduce',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de ferro em pó' },
    componentsText: 'V, S, M (uma pitada de ferro em pó)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura ou objeto a até 9 m faz salvaguarda de Constituição (se for criatura não voluntária) ou é ampliada/reduzida. Ampliar: +1d4 no dano e vantagem em Força; Reduzir: −1d4 e desvantagem.',
    save: 'constitution',
    classes: [],
  },
  {
    id: 'enthrall',
    namePt: 'Cativar',
    nameEn: 'Enthrall',
    level: 2,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Você faz um discurso cativante. Criaturas à sua escolha a até 18 m que possam ouvi-lo fazem salvaguarda de Sabedoria ou têm desvantagem em Percepção passiva para notar outras criaturas.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'find-steed',
    namePt: 'Encontrar Corcel',
    nameEn: 'Find Steed',
    level: 2,
    school: 'conjuration',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você convoca um espírito que assume a forma leal de um corcel (cavalo, pônei, camelo, alce ou mastim). Ele tem inteligência, pode agir de modo independente e serve de montaria.',
    classes: [],
  },
  {
    id: 'find-traps',
    namePt: 'Encontrar Armadilhas',
    nameEn: 'Find Traps',
    level: 2,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você sente a presença de qualquer armadilha dentro de 36 m que esteja na sua linha de visão. A magia revela a natureza geral do perigo, mas não a localização exata.',
    classes: [],
  },
  {
    id: 'flame-blade',
    namePt: 'Lâmina Flamejante',
    nameEn: 'Flame Blade',
    level: 2,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma folha de sumagre' },
    componentsText: 'V, S, M (uma folha de sumagre)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma lâmina incandescente de fogo aparece na sua mão, emitindo luz. Você pode usar uma ação para fazer um ataque de magia corpo a corpo: se acertar, causa 3d6 de dano de fogo.',
    attack: 'melee',
    damage: [{ count: 3, sides: 6, bonus: 0, type: 'Fogo' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'flaming-sphere',
    namePt: 'Esfera Flamejante',
    nameEn: 'Flaming Sphere',
    level: 2,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'sphere', sizeMeters: 1.5 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'sebo, enxofre e pó de ferro' },
    componentsText: 'V, S, M (sebo, enxofre e pó de ferro)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma esfera de fogo de 1,5 m de diâmetro aparece. Uma criatura que termine o turno a até 1,5 m dela faz salvaguarda de Destreza ou sofre 2d6 de dano de fogo. Com uma ação bônus, você move a esfera até 9 m.',
    save: 'dexterity',
    damage: [{ count: 2, sides: 6, bonus: 0, type: 'Fogo' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'gentle-repose',
    namePt: 'Repouso Tranquilo',
    nameEn: 'Gentle Repose',
    level: 2,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de sal e algumas moedas de cobre' },
    componentsText: 'V, S, M (uma pitada de sal e algumas moedas de cobre)',
    duration: '10 dias',
    concentration: false,
    ritual: true,
    description:
      'Um cadáver que você toca fica protegido da decomposição e não pode virar morto-vivo enquanto a magia durar.',
    classes: [],
  },
  {
    id: 'gust-of-wind',
    namePt: 'Rajada de Vento',
    nameEn: 'Gust of Wind',
    level: 2,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'line', sizeMeters: 18 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma semente de legume' },
    componentsText: 'V, S, M (uma semente de legume)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma forte rajada de vento de 18 m de comprimento e 3 m de largura sopra de você. Cada criatura na área faz salvaguarda de Força ou é empurrada 4,5 m; o vento dispersa névoa e apaga chamas.',
    save: 'strength',
    classes: [],
  },
  {
    id: 'heat-metal',
    namePt: 'Metal em Brasa',
    nameEn: 'Heat Metal',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de ferro e uma chama' },
    componentsText: 'V, S, M (um pedaço de ferro e uma chama)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Escolha um objeto de metal manufaturado a até 18 m. Quem estiver segurando-o sofre 2d8 de dano de fogo (salvaguarda de Constituição para metade) e, se falhar, tem desvantagem nos ataques e testes até o início do seu próximo turno.',
    save: 'constitution',
    damage: [{ count: 2, sides: 8, bonus: 0, type: 'Fogo' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'hold-person',
    namePt: 'Imobilizar Pessoa',
    nameEn: 'Hold Person',
    level: 2,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pequeno pedaço reto de ferro' },
    componentsText: 'V, S, M (um pequeno pedaço reto de ferro)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Um humanoide a até 18 m faz salvaguarda de Sabedoria ou fica paralisado, repetindo a salvaguarda no fim de cada turno.',
    save: 'wisdom',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'invisibility',
    namePt: 'Invisibilidade',
    nameEn: 'Invisibility',
    level: 2,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um cílio num pedaço de goma arábica' },
    componentsText: 'V, S, M (um cílio num pedaço de goma arábica)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura que você toca fica invisível até a magia acabar. A magia termina se o alvo atacar ou lançar uma magia.',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'knock',
    namePt: 'Abrir',
    nameEn: 'Knock',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Escolha um objeto a até 18 m travado, preso ou trancado magicamente. Ele se abre, destranca ou solta com um estrondo alto (ou a Tranca Arcana é suprimida por 10 min).',
    classes: [],
  },
  {
    id: 'lesser-restoration',
    namePt: 'Restauração Menor',
    nameEn: 'Lesser Restoration',
    level: 2,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura que você toca acaba com uma doença ou uma condição: cegueira, surdez, paralisia, envenenamento ou envenenada.',
    classes: [],
  },
  {
    id: 'levitate',
    namePt: 'Levitar',
    nameEn: 'Levitate',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pequeno laço de arame' },
    componentsText: 'V, S, M (um pequeno laço de arame)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura (salvaguarda de Constituição) ou objeto a até 18 m flutua verticalmente, subindo ou descendo até 6 m por rodada. Você pode mover o alvo horizontalmente puxando-se.',
    save: 'constitution',
    classes: [],
  },
  {
    id: 'locate-animals-or-plants',
    namePt: 'Localizar Animais ou Plantas',
    nameEn: 'Locate Animals or Plants',
    level: 2,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pelo de um cão de caça' },
    componentsText: 'V, S, M (pelo de um cão de caça)',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    description:
      'Escolha uma espécie de besta ou planta. Você sente a direção e a distância da criatura/planta mais próxima dessa espécie a até 7,5 km.',
    classes: [],
  },
  {
    id: 'locate-object',
    namePt: 'Localizar Objeto',
    nameEn: 'Locate Object',
    level: 2,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um galho bifurcado' },
    componentsText: 'V, S, M (um galho bifurcado)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Descreva um objeto conhecido: você sente a direção e a distância dele a até 300 m. A magia bloqueia se chumbo, ouro ou uma magia de proteção interpuser.',
    classes: [],
  },
  {
    id: 'magic-mouth',
    namePt: 'Boca Mágica',
    nameEn: 'Magic Mouth',
    level: 2,
    school: 'illusion',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um favo de mel e pó de jade no valor de 10 PO, consumidos' },
    componentsText: 'V, S, M (um favo de mel e pó de jade no valor de 10 PO, consumidos)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: true,
    description:
      'Você implanta uma mensagem numa ilusão que repete até 25 palavras quando a condição que você definir ocorrer (ex.: uma criatura se aproximar).',
    classes: [],
  },
  {
    id: 'magic-weapon',
    namePt: 'Arma Mágica',
    nameEn: 'Magic Weapon',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma arma não mágica que você toca fica mágica, com +1 nas jogadas de ataque e de dano.',
    upcast: { note: 'O bônus vira +2 com espaço de 4º/5º nível e +3 com espaço de 6º ou superior.' },
    classes: [],
  },
  {
    id: 'melfs-acid-arrow',
    namePt: 'Flecha Ácida de Melf',
    nameEn: "Melf's Acid Arrow",
    level: 2,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'folha de ruibarbo em pó e estômago de víbora' },
    componentsText: 'V, S, M (folha de ruibarbo em pó e estômago de víbora)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Faça um ataque de magia à distância. Se acertar, o alvo sofre 4d4 de dano de ácido imediatamente e 2d4 no fim do próximo turno dele.',
    attack: 'ranged',
    damage: [{ count: 4, sides: 4, bonus: 0, type: 'Ácido' }],
    upcast: { extraDicePerSlot: 1, note: 'Some 1d4 ao dano normal e ao dano do turno seguinte por nível acima do 2º.' },
    classes: [],
  },
  {
    id: 'mirror-image',
    namePt: 'Imagem Espelhada',
    nameEn: 'Mirror Image',
    level: 2,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Três duplicatas ilusórias de você aparecem. Cada vez que uma criatura o ataca, ela pode acertar uma duplicata (que se dissipa) em vez de você, conforme a rolagem.',
    classes: [],
  },
  {
    id: 'misty-step',
    namePt: 'Passo Enevoado',
    nameEn: 'Misty Step',
    level: 2,
    school: 'conjuration',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Envolto em névoa prateada, você se teleporta até 9 m para um espaço desocupado que possa ver.',
    classes: [],
  },
  {
    id: 'moonbeam',
    namePt: 'Raio Lunar',
    nameEn: 'Moonbeam',
    level: 2,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'cylinder', sizeMeters: 1.5, note: '1,5 m de raio, 12 m de altura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pedra da lua e uma semente de lua' },
    componentsText: 'V, S, M (uma pedra da lua e uma semente de lua)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Um raio prateado cilíndrico cai num ponto a até 36 m. Uma criatura que entre na área ou comece o turno ali faz salvaguarda de Constituição ou sofre 2d10 de dano radiante (metade se passar), com desvantagem se for um metamorfo. Com uma ação, você move o raio 18 m.',
    save: 'constitution',
    damage: [{ count: 2, sides: 10, bonus: 0, type: 'Radiante' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'nystuls-magic-aura',
    namePt: 'Aura Mágica de Nystul',
    nameEn: "Nystul's Magic Aura",
    level: 2,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pequeno quadrado de seda' },
    componentsText: 'V, S, M (um pequeno quadrado de seda)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Você altera a aura de uma criatura ou objeto para enganar magias de detecção: pode mudar o tipo de criatura, disfarçar magias ativas ou fazer um objeto parecer não mágico.',
    classes: [],
  },
  {
    id: 'pass-without-trace',
    namePt: 'Passar sem Deixar Rastro',
    nameEn: 'Pass without Trace',
    level: 2,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'cinzas de visco e uma folha de abeto' },
    componentsText: 'V, S, M (cinzas de visco e uma folha de abeto)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você e as criaturas à sua escolha a até 9 m recebem +10 em Furtividade e não podem ser rastreadas por meios não mágicos.',
    classes: [],
  },
  {
    id: 'phantasmal-force',
    namePt: 'Força Fantasmagórica',
    nameEn: 'Phantasmal Force',
    level: 2,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'cube', sizeMeters: 3 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de velo' },
    componentsText: 'V, S, M (um pedaço de velo)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você cria uma ilusão psíquica num cubo de 3 m que só o alvo percebe. Se ele falhar numa salvaguarda de Inteligência, acredita na ilusão e sofre 1d6 de dano psíquico por turno se interagir com ela.',
    save: 'intelligence',
    damage: [{ count: 1, sides: 6, bonus: 0, type: 'Psíquico' }],
    classes: [],
  },
  {
    id: 'prayer-of-healing',
    namePt: 'Prece de Cura',
    nameEn: 'Prayer of Healing',
    level: 2,
    school: 'evocation',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Até seis criaturas a até 9 m recuperam 2d8 + o seu modificador de atributo de conjuração em pontos de vida cada uma. Não afeta mortos-vivos nem constructos.',
    healing: { count: 2, sides: 8, bonus: 0, type: null },
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'protection-from-poison',
    namePt: 'Proteção contra Veneno',
    nameEn: 'Protection from Poison',
    level: 2,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura que você toca neutraliza um veneno, tem vantagem em salvaguardas contra envenenamento e resistência a dano de veneno por 1 h.',
    classes: [],
  },
  {
    id: 'ray-of-enfeeblement',
    namePt: 'Raio de Enfraquecimento',
    nameEn: 'Ray of Enfeeblement',
    level: 2,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura a até 18 m faz salvaguarda de Constituição ou causa apenas metade do dano com ataques de arma até a magia acabar. Repete a salvaguarda no fim de cada turno.',
    save: 'constitution',
    classes: [],
  },
  {
    id: 'rope-trick',
    namePt: 'Truque de Corda',
    nameEn: 'Rope Trick',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'extrato de milho e papel torcido' },
    componentsText: 'V, S, M (extrato de milho e papel torcido)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma corda que você toca se ergue no ar e leva a um espaço extradimensional invisível de 3 m × 1,5 m, onde até oito criaturas podem se esconder.',
    classes: [],
  },
  {
    id: 'scorching-ray',
    namePt: 'Raio Escaldante',
    nameEn: 'Scorching Ray',
    level: 2,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você cria três raios de fogo e os arremessa separadamente ou contra o mesmo alvo. Faça um ataque de magia à distância por raio: cada acerto causa 2d6 de dano de fogo.',
    attack: 'ranged',
    damage: [{ count: 2, sides: 6, bonus: 0, type: 'Fogo' }],
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'see-invisibility',
    namePt: 'Ver o Invisível',
    nameEn: 'See Invisibility',
    level: 2,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de talco e prata em pó' },
    componentsText: 'V, S, M (uma pitada de talco e prata em pó)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Por 1 h você vê criaturas e objetos invisíveis como se fossem visíveis, e enxerga o Plano Etéreo até 18 m.',
    classes: [],
  },
  {
    id: 'shatter',
    namePt: 'Estilhaçar',
    nameEn: 'Shatter',
    level: 2,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'sphere', sizeMeters: 3 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um caco de mica' },
    componentsText: 'V, S, M (um caco de mica)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Um estrondo doloroso explode numa esfera de 3 m de raio. Cada criatura na área faz salvaguarda de Constituição ou sofre 3d8 de dano de trovão (metade se passar); construtos de pedra/metal têm desvantagem.',
    save: 'constitution',
    damage: [{ count: 3, sides: 8, bonus: 0, type: 'Trovão' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'silence',
    namePt: 'Silêncio',
    nameEn: 'Silence',
    level: 2,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: true,
    description:
      'Nenhum som pode ser criado dentro nem atravessar uma esfera de 6 m de raio. Criaturas dentro ficam surdas e não podem lançar magias com componente verbal.',
    classes: [],
  },
  {
    id: 'spider-climb',
    namePt: 'Escalada de Aranha',
    nameEn: 'Spider Climb',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gota de betume e uma aranha' },
    componentsText: 'V, S, M (uma gota de betume e uma aranha)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura voluntária que você toca pode se mover pelas paredes e tetos e tem o deslocamento de escalada igual ao de caminhada.',
    classes: [],
  },
  {
    id: 'spike-growth',
    namePt: 'Crescimento de Espinhos',
    nameEn: 'Spike Growth',
    level: 2,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'sete espinhos afiados' },
    componentsText: 'V, S, M (sete espinhos afiados)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'O solo numa esfera de 6 m de raio fica coberto de espinhos. A área é terreno difícil e cada criatura que se mover por ela sofre 2d4 de dano perfurante a cada 1,5 m percorrido.',
    damage: [{ count: 2, sides: 4, bonus: 0, type: 'Perfurante' }],
    classes: [],
  },
  {
    id: 'spiritual-weapon',
    namePt: 'Arma Espiritual',
    nameEn: 'Spiritual Weapon',
    level: 2,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Uma arma flutuante de força aparece e ataca. Com uma ação bônus, você pode movê-la até 6 m e fazer um ataque de magia corpo a corpo contra uma criatura a até 1,5 m dela: 1d8 + o modificador de conjuração de dano de força.',
    attack: 'melee',
    damage: [{ count: 1, sides: 8, bonus: 0, type: 'Força' }],
    upcast: { note: 'O dano aumenta em 1d8 a cada dois níveis de espaço acima do 2º.' },
    classes: [],
  },
  {
    id: 'suggestion',
    namePt: 'Sugestão',
    nameEn: 'Suggestion',
    level: 2,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: false, material: true },
    material: { text: 'uma língua de cobra e um favo de mel' },
    componentsText: 'M (uma língua de cobra e um favo de mel)',
    duration: 'Concentração, até 8 horas',
    concentration: true,
    ritual: false,
    description:
      'Você sugere um curso de ação a uma criatura que possa ouvi-lo. Se ela falhar numa salvaguarda de Sabedoria, segue a sugestão razoável enquanto a magia durar; a magia acaba se ela sofrer dano de você ou de aliados.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'warding-bond',
    namePt: 'Vínculo Protetor',
    nameEn: 'Warding Bond',
    level: 2,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um par de anéis de platina no valor de 50 PO cada' },
    componentsText: 'V, S, M (um par de anéis de platina no valor de 50 PO cada)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura voluntária que você toca ganha +1 de CA e salvaguardas e resistência a todo dano; cada vez que ela sofre dano, você sofre a mesma quantidade.',
    classes: [],
  },
  {
    id: 'web',
    namePt: 'Teia',
    nameEn: 'Web',
    level: 2,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'cube', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de teia de aranha' },
    componentsText: 'V, S, M (um pedaço de teia de aranha)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Teias espessas preenchem um cubo de 6 m. Cada criatura que comece o turno nelas ou entre faz salvaguarda de Destreza ou fica impedida; quem falhar pode repetir a salvaguarda.',
    save: 'dexterity',
    classes: [],
  },
  {
    id: 'zone-of-truth',
    namePt: 'Zona da Verdade',
    nameEn: 'Zone of Truth',
    level: 2,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'sphere', sizeMeters: 4.5 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '10 minutos',
    concentration: false,
    ritual: false,
    description:
      'Uma esfera de 4,5 m de raio impede mentiras deliberadas. Cada criatura que entre na área faz salvaguarda de Carisma ou fica incapaz de dizer uma mentira; você sabe quem passou na salvaguarda.',
    save: 'charisma',
    classes: [],
  },
];
