import type { Spell } from '../types.js';

/**
 * Magias de 8º nível do PHB 2014 (18). Ordem alfabética pelo nome em inglês.
 * `classes` fica VAZIO até o Prompt 6.2.
 */
export const LEVEL_8: readonly Spell[] = [
  {
    id: 'animal-shapes',
    namePt: 'Formas Animais',
    nameEn: 'Animal Shapes',
    level: 8,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 24 horas',
    concentration: true,
    ritual: false,
    description:
      'Criaturas voluntárias a até 9 m se transformam em bestas de NC 4 ou menos. Cada alvo assume a forma à sua escolha e pode mudar de forma novamente com uma ação.',
    classes: [],
  },
  {
    id: 'antimagic-field',
    namePt: 'Campo Antimagia',
    nameEn: 'Antimagic Field',
    level: 8,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'sphere', sizeMeters: 3, note: 'origem em você' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de ferro em pó ou limalha de ferro' },
    componentsText: 'V, S, M (ferro em pó ou limalha de ferro)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma esfera invisível de 3 m de raio suprime magia. Dentro dela, magias não funcionam, itens mágicos perdem propriedades e criaturas conjuradas somem temporariamente.',
    classes: [],
  },
  {
    id: 'antipathy-sympathy',
    namePt: 'Antipatia/Simpatia',
    nameEn: 'Antipathy/Sympathy',
    level: 8,
    school: 'enchantment',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'alume e vinagre (antipatia) ou mel (simpatia)' },
    componentsText: 'V, S, M (alume e vinagre ou mel)',
    duration: '10 dias',
    concentration: false,
    ritual: false,
    description:
      'Você imbui um objeto ou área com atração ou repulsa. Criaturas do tipo escolhido fazem salvaguarda de Sabedoria: na antipatia, fogem; na simpatia, são atraídas para perto.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'clone',
    namePt: 'Clone',
    nameEn: 'Clone',
    level: 8,
    school: 'necromancy',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um diamante no valor de 1000 PO e um vaso selado de 2000 PO, com carne da criatura' },
    componentsText: 'V, S, M (um diamante de 1000 PO e um vaso de 2000 PO)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você cria um clone inerte de uma criatura viva. Se a criatura morrer, sua alma passa para o clone, que desperta com todos os PV após 120 dias.',
    classes: [],
  },
  {
    id: 'control-weather',
    namePt: 'Controlar o Clima',
    nameEn: 'Control Weather',
    level: 8,
    school: 'transmutation',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'sphere', sizeMeters: 7500, note: 'raio de 7,5 km' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'incenso aceso e pedaços de terra e madeira' },
    componentsText: 'V, S, M (incenso aceso, terra e madeira)',
    duration: 'Concentração, até 8 horas',
    concentration: true,
    ritual: false,
    description:
      'Você assume controle do clima num raio de 7,5 km: escolhe precipitação, temperatura e vento, alterando o clima em estágios a cada 1d4 × 10 min.',
    classes: [],
  },
  {
    id: 'demiplane',
    namePt: 'Demiplano',
    nameEn: 'Demiplane',
    level: 8,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: false, somatic: true, material: false },
    componentsText: 'S',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Você abre uma porta para uma sala extradimensional com 9 m de cada lado. Você pode criar um demi-plano novo ou abrir um que já criou antes.',
    classes: [],
  },
  {
    id: 'dominate-monster',
    namePt: 'Dominar Monstro',
    nameEn: 'Dominate Monster',
    level: 8,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Qualquer criatura a até 18 m faz salvaguarda de Sabedoria ou fica enfeitiçada e sob seu controle. Você pode usar uma ação para comandá-la; tem vantagem se estiver lutando com ela.',
    save: 'wisdom',
    upcast: { note: 'Com espaço de 9º nível dura até 8 horas.' },
    classes: [],
  },
  {
    id: 'earthquake',
    namePt: 'Terremoto',
    nameEn: 'Earthquake',
    level: 8,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '150 m',
    rangeKind: 'ranged',
    rangeMeters: 150,
    area: { shape: 'sphere', sizeMeters: 30 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pouco de terra, rocha e argila' },
    componentsText: 'V, S, M (terra, rocha e argila)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Um tremor sacode um círculo de 30 m de raio. O solo vira terreno difícil, criaturas no chão fazem salvaguarda de Destreza ou caem prostradas, e você pode abrir fissuras e derrubar estruturas.',
    save: 'dexterity',
    classes: [],
  },
  {
    id: 'feeblemind',
    namePt: 'Debilitar Mente',
    nameEn: 'Feeblemind',
    level: 8,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um punhado de argila, cristal, osso ou esfera de cristal' },
    componentsText: 'V, S, M (argila, cristal, osso ou esfera)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura a até 45 m faz salvaguarda de Inteligência. Se falhar, sofre 4d6 de dano psíquico e a INT e o CAR dela caem para 1, não podendo lançar magias nem entender idiomas até ser curada.',
    save: 'intelligence',
    damage: [{ count: 4, sides: 6, bonus: 0, type: 'Psíquico' }],
    classes: [],
  },
  {
    id: 'glibness',
    namePt: 'Lábia',
    nameEn: 'Glibness',
    level: 8,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Sua lábia fica impecável: você pode substituir o resultado de um teste de Carisma por 15, e quem tentar descobrir se você está mentindo sempre acredita no que diz.',
    classes: [],
  },
  {
    id: 'holy-aura',
    namePt: 'Aura Sagrada',
    nameEn: 'Holy Aura',
    level: 8,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um relicário no valor de 1000 PO' },
    componentsText: 'V, S, M (um relicário no valor de 1000 PO)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma aura sagrada irradia de você. Criaturas à sua escolha a até 9 m têm vantagem em salvaguardas, resistência a todo dano e, se um corruptor ou morto-vivo as acertar em corpo a corpo, fica cego.',
    classes: [],
  },
  {
    id: 'incendiary-cloud',
    namePt: 'Nuvem Incendiária',
    nameEn: 'Incendiary Cloud',
    level: 8,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma nuvem de fumaça incandescente de 6 m de raio aparece. Cada criatura na área faz salvaguarda de Destreza ou sofre 10d8 de dano de fogo (metade se passar); a nuvem se move 3 m por turno.',
    save: 'dexterity',
    damage: [{ count: 10, sides: 8, bonus: 0, type: 'Fogo' }],
    classes: [],
  },
  {
    id: 'maze',
    namePt: 'Labirinto',
    nameEn: 'Maze',
    level: 8,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura a até 18 m é aprisionada num labirinto de minotauros por 10 min. Ela pode usar a ação para tentar escapar com um teste de Inteligência (CD 20).',
    classes: [],
  },
  {
    id: 'mind-blank',
    namePt: 'Mente em Branco',
    nameEn: 'Mind Blank',
    level: 8,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura voluntária fica imune a dano psíquico e a magias de leitura de mente, adivinhação e detecção de emoções por 24 h.',
    classes: [],
  },
  {
    id: 'power-word-stun',
    namePt: 'Palavra de Poder: Atordoar',
    nameEn: 'Power Word Stun',
    level: 8,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você pronuncia uma palavra de poder a uma criatura a até 18 m. Se ela tiver 150 PV ou menos, fica atordoada; ela repete uma salvaguarda de Constituição no fim de cada turno para se libertar.',
    save: 'constitution',
    classes: [],
  },
  {
    id: 'sunburst',
    namePt: 'Explosão Solar',
    nameEn: 'Sunburst',
    level: 8,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'sphere', sizeMeters: 18 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pedra do sol' },
    componentsText: 'V, S, M (uma pedra do sol)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma luz solar brilhante explode numa esfera de 18 m de raio. Cada criatura na área faz salvaguarda de Constituição ou sofre 12d6 de dano radiante e fica cega por 1 min (metade e sem cegueira se passar).',
    save: 'constitution',
    damage: [{ count: 12, sides: 6, bonus: 0, type: 'Radiante' }],
    classes: [],
  },
  {
    id: 'telepathy',
    namePt: 'Telepatia',
    nameEn: 'Telepathy',
    level: 8,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um par de anéis de prata enlaçados' },
    componentsText: 'V, S, M (um par de anéis de prata enlaçados)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Você cria um vínculo telepático com uma criatura voluntária a até 9 m. Enquanto durar, vocês podem trocar mensagens mentais a qualquer distância no mesmo plano.',
    classes: [],
  },
  {
    id: 'tsunami',
    namePt: 'Tsunami',
    nameEn: 'Tsunami',
    level: 8,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Visão',
    rangeKind: 'sight',
    area: { shape: 'line', sizeMeters: 90, note: 'muralha de água de 90 m de comprimento e 90 m de altura' },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 6 rodadas',
    concentration: true,
    ritual: false,
    description:
      'Uma muralha de água de 90 m de comprimento e 90 m de altura aparece e varre a área que você indicar. Cada criatura na área faz salvaguarda de Força ou sofre 6d10 de dano de concussão e é arrastada.',
    save: 'strength',
    damage: [{ count: 6, sides: 10, bonus: 0, type: 'Concussão' }],
    classes: [],
  },
];
