import type { Spell } from '../types.js';

/**
 * Magias de 9º nível do PHB 2014 (16). Ordem alfabética pelo nome em inglês.
 * `classes` fica VAZIO até o Prompt 6.2.
 */
export const LEVEL_9: readonly Spell[] = [
  {
    id: 'astral-projection',
    namePt: 'Projeção Astral',
    nameEn: 'Astral Projection',
    level: 9,
    school: 'necromancy',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um jacinto no valor de 1000 PO e barras de prata de 100 PO por criatura, consumidos' },
    componentsText: 'V, S, M (jacinto de 1000 PO e prata de 100 PO por criatura, consumidos)',
    duration: 'Especial',
    concentration: false,
    ritual: false,
    description:
      'Você e até oito criaturas projetam seus corpos astrais no Plano Astral, deixando os corpos físicos em animação suspensa. Um fio de prata liga cada corpo ao seu corpo astral.',
    classes: [],
  },
  {
    id: 'foresight',
    namePt: 'Previsão',
    nameEn: 'Foresight',
    level: 9,
    school: 'divination',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pena de beija-flor' },
    componentsText: 'V, S, M (uma pena de beija-flor)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura voluntária que você toca não pode ser surpreendida, tem vantagem em ataques, testes de atributo e salvaguardas, e outras criaturas têm desvantagem nos ataques contra ela.',
    classes: [],
  },
  {
    id: 'gate',
    namePt: 'Portão',
    nameEn: 'Gate',
    level: 9,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um diamante no valor de 5000 PO' },
    componentsText: 'V, S, M (um diamante no valor de 5000 PO)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você abre um portal para outro plano e nomeia uma criatura específica, que pode ser puxada através dele (salvaguarda de Carisma para resistir). Você pode também viajar para outro plano.',
    save: 'charisma',
    classes: [],
  },
  {
    id: 'imprisonment',
    namePt: 'Aprisionamento',
    nameEn: 'Imprisonment',
    level: 9,
    school: 'abjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma representação do alvo e um componente especial (ver descrição)' },
    componentsText: 'V, S, M (uma representação do alvo e um componente especial)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: false,
    description:
      'Você aprisiona uma criatura para sempre. Escolha uma forma (sono eterno, enterrada, acorrentada, minúscula, em sono, metempsicose). Cada forma exige um componente material raro.',
    classes: [],
  },
  {
    id: 'mass-heal',
    namePt: 'Cura em Massa',
    nameEn: 'Mass Heal',
    level: 9,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma onda de energia curativa distribui até 700 pontos de vida entre criaturas à sua escolha a até 18 m. Mortos-vivos e constructos não são afetados.',
    healing: { count: 0, sides: 0, bonus: 700, type: null },
    classes: [],
  },
  {
    id: 'meteor-swarm',
    namePt: 'Chuva de Meteoros',
    nameEn: 'Meteor Swarm',
    level: 9,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '1,5 km',
    rangeKind: 'ranged',
    rangeMeters: 1500,
    area: { shape: 'sphere', sizeMeters: 12, note: 'quatro esferas de 12 m de raio' },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Quatro esferas de fogo caem em pontos que você enxergue. Cada criatura numa esfera faz salvaguarda de Destreza: se falhar, sofre 20d6 de dano de fogo e 20d6 de dano de concussão; se passar, metade.',
    save: 'dexterity',
    damage: [
      { count: 20, sides: 6, bonus: 0, type: 'Fogo' },
      { count: 20, sides: 6, bonus: 0, type: 'Concussão' },
    ],
    classes: [],
  },
  {
    id: 'power-word-heal',
    namePt: 'Palavra de Poder: Curar',
    nameEn: 'Power Word Heal',
    level: 9,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura que você toca recupera todos os pontos de vida e, se estiver atordoada, amedrontada, paralisada ou enfeitiçada, essas condições acabam.',
    classes: [],
  },
  {
    id: 'power-word-kill',
    namePt: 'Palavra de Poder: Matar',
    nameEn: 'Power Word Kill',
    level: 9,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você pronuncia uma palavra de poder a uma criatura a até 18 m. Se ela tiver 100 pontos de vida ou menos, morre imediatamente.',
    classes: [],
  },
  {
    id: 'prismatic-wall',
    namePt: 'Muralha Prismática',
    nameEn: 'Prismatic Wall',
    level: 9,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '10 minutos',
    concentration: false,
    ritual: false,
    description:
      'Uma parede de luz multicolorida surge, com sete camadas. Cada camada tem um efeito diferente (dano de um tipo, cegueira, petrificação etc.) e só pode ser destruída com meios específicos.',
    damage: [
      { count: 10, sides: 6, bonus: 0, type: 'Fogo' },
      { count: 10, sides: 6, bonus: 0, type: 'Ácido' },
      { count: 10, sides: 6, bonus: 0, type: 'Elétrico' },
      { count: 10, sides: 6, bonus: 0, type: 'Veneno' },
    ],
    classes: [],
  },
  {
    id: 'shapechange',
    namePt: 'Mudança de Forma',
    nameEn: 'Shapechange',
    level: 9,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um diadema de jade no valor de 1500 PO' },
    componentsText: 'V, S, M (um diadema de jade no valor de 1500 PO)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você assume a forma de outra criatura (mantendo alinhamento e personalidade) e pode trocar de forma com uma ação. Você mantém o controle e a capacidade de falar.',
    classes: [],
  },
  {
    id: 'storm-of-vengeance',
    namePt: 'Tempestade de Vingança',
    nameEn: 'Storm of Vengeance',
    level: 9,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Visão',
    rangeKind: 'sight',
    area: { shape: 'sphere', sizeMeters: 90, note: 'raio de 90 m' },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma nuvem de tempestade de 90 m de raio se forma. A cada rodada, produz um efeito diferente: trovão, chuva ácida, raios, granizo, tempestade de vento e chuva congelante, cada um com dano e salvaguarda.',
    save: 'constitution',
    damage: [{ count: 2, sides: 6, bonus: 0, type: 'Trovão' }],
    classes: [],
  },
  {
    id: 'time-stop',
    namePt: 'Parar o Tempo',
    nameEn: 'Time Stop',
    level: 9,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você interrompe brevemente o fluxo do tempo e age livremente por 1d4 + 1 turnos consecutivos. A magia termina se você afetar outra criatura ou um objeto sendo carregado por alguém.',
    classes: [],
  },
  {
    id: 'true-polymorph',
    namePt: 'Polimorfia Verdadeira',
    nameEn: 'True Polymorph',
    level: 9,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gota de mercúrio, goma arábica e um pouco de fumaça' },
    componentsText: 'V, S, M (mercúrio, goma arábica e fumaça)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você transforma uma criatura em outra criatura, uma criatura num objeto ou um objeto numa criatura. Se mantiver a concentração por 1 h, a transformação fica permanente.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'true-resurrection',
    namePt: 'Ressurreição Verdadeira',
    nameEn: 'True Resurrection',
    level: 9,
    school: 'necromancy',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'água benta e diamantes no valor de 25000 PO, consumidos' },
    componentsText: 'V, S, M (água benta e diamantes de 25000 PO, consumidos)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma criatura morta há até 200 anos (ou os restos dela) e a traz de volta à vida com todos os PV. Não funciona em quem morreu de velhice; cura todas as feridas e doenças.',
    classes: [],
  },
  {
    id: 'weird',
    namePt: 'Terror',
    nameEn: 'Weird',
    level: 9,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'sphere', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você puxa os medos de criaturas numa esfera de 9 m de raio. Cada uma faz salvaguarda de Sabedoria ou fica amedrontada e, a cada turno, sofre 4d10 de dano psíquico até a magia acabar.',
    save: 'wisdom',
    damage: [{ count: 4, sides: 10, bonus: 0, type: 'Psíquico' }],
    classes: [],
  },
  {
    id: 'wish',
    namePt: 'Desejo',
    nameEn: 'Wish',
    level: 9,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'A magia mais poderosa: você pode duplicar qualquer magia de 8º nível ou menos, criar um objeto, curar todas as criaturas, conceder resistência ou reescrever um evento. Usos além disso podem custar muito caro.',
    classes: [],
  },
];
