import type { Spell } from '../types.js';

/**
 * Magias de 6º nível do PHB 2014 (32). Ordem alfabética pelo nome em inglês.
 * `classes` fica VAZIO até o Prompt 6.2.
 */
export const LEVEL_6: readonly Spell[] = [
  {
    id: 'arcane-gate',
    namePt: 'Portal Arcano',
    nameEn: 'Arcane Gate',
    level: 6,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '150 m',
    rangeKind: 'ranged',
    rangeMeters: 150,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Você cria dois portais interligados de 3 m em pontos que possa ver a até 150 m. Qualquer coisa que entre num deles sai pelo outro; você pode mudar a orientação dos portais com uma ação bônus.',
    classes: [],
  },
  {
    id: 'blade-barrier',
    namePt: 'Barreira de Lâminas',
    nameEn: 'Blade Barrier',
    level: 6,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    area: { shape: 'line', sizeMeters: 30, note: 'ou anel de 18 m de raio, 6 m de altura' },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma parede de lâminas giratórias surge. Cada criatura que entre na área ou comece o turno ali faz salvaguarda de Destreza ou sofre 6d10 de dano cortante (metade se passar); a área é de cobertura total.',
    save: 'dexterity',
    damage: [{ count: 6, sides: 10, bonus: 0, type: 'Cortante' }],
    classes: [],
  },
  {
    id: 'chain-lightning',
    namePt: 'Corrente de Raios',
    nameEn: 'Chain Lightning',
    level: 6,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pouco de pelo, uma haste de vidro e um alfinete de prata' },
    componentsText: 'V, S, M (pelo, haste de vidro e um alfinete de prata)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Um raio salta de você a um alvo a até 45 m, e três raios secundários saltam dele para outros alvos à escolha. Cada alvo faz salvaguarda de Destreza ou sofre 10d8 de dano elétrico (metade se passar).',
    save: 'dexterity',
    damage: [{ count: 10, sides: 8, bonus: 0, type: 'Elétrico' }],
    upcast: { extraTargetsPerSlot: 1, note: 'Um raio secundário adicional por nível de espaço acima do 6º.' },
    classes: [],
  },
  {
    id: 'circle-of-death',
    namePt: 'Círculo da Morte',
    nameEn: 'Circle of Death',
    level: 6,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'sphere', sizeMeters: 18 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pó de uma pérola negra esmagada no valor de 500 PO' },
    componentsText: 'V, S, M (pó de pérola negra de 500 PO)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma onda de energia negativa varre uma esfera de 18 m de raio. Cada criatura na área faz salvaguarda de Constituição ou sofre 8d6 de dano necrótico (metade se passar).',
    save: 'constitution',
    damage: [{ count: 8, sides: 6, bonus: 0, type: 'Necrótico' }],
    upcast: { extraDicePerSlot: 2 },
    classes: [],
  },
  {
    id: 'conjure-fey',
    namePt: 'Convocar Fada',
    nameEn: 'Conjure Fey',
    level: 6,
    school: 'conjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você invoca uma criatura feérica de NC 6 ou menos, que obedece às suas ordens. Se perder a concentração, a criatura pode ficar hostil.',
    upcast: { note: 'O NC máximo aumenta em 1 por nível de espaço acima do 6º.' },
    classes: [],
  },
  {
    id: 'contingency',
    namePt: 'Contingência',
    nameEn: 'Contingency',
    level: 6,
    school: 'evocation',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma estatueta de você mesmo no valor de 1500 PO' },
    componentsText: 'V, S, M (uma estatueta de você mesmo no valor de 1500 PO)',
    duration: '10 dias',
    concentration: false,
    ritual: false,
    description:
      'Você prepara uma magia de até 5º nível para entrar em ação sob uma condição que descrever. Quando a condição ocorrer, a magia é lançada sobre você automaticamente.',
    classes: [],
  },
  {
    id: 'create-undead',
    namePt: 'Criar Mortos-Vivos',
    nameEn: 'Create Undead',
    level: 6,
    school: 'necromancy',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pote de barro com terra de sepultura, sangue e ônix negro no valor de 150 PO por cadáver' },
    componentsText: 'V, S, M (terra de sepultura, sangue e ônix negro de 150 PO)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você anima até três cadáveres como carniçais por 24 h, obedecendo às suas ordens verbais. Para renovar o controle, é preciso conjurar de novo.',
    upcast: { note: 'Com espaço de 7º ou superior cria mortos-vivos mais poderosos (7º: 4 carniçais etc.).' },
    classes: [],
  },
  {
    id: 'disintegrate',
    namePt: 'Desintegrar',
    nameEn: 'Disintegrate',
    level: 6,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pedra-ímã e uma pitada de poeira' },
    componentsText: 'V, S, M (uma pedra-ímã e uma pitada de poeira)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Um raio verde atinge um alvo a até 18 m. Ele faz salvaguarda de Destreza ou sofre 10d6 + 40 de dano de força; se isso o reduzir a 0 PV, vira pó. Objetos grandes são desintegrados.',
    save: 'dexterity',
    damage: [{ count: 10, sides: 6, bonus: 40, type: 'Força' }],
    upcast: { extraDicePerSlot: 3 },
    classes: [],
  },
  {
    id: 'drawmijs-instant-summons',
    namePt: 'Convocação Instantânea de Drawmij',
    nameEn: "Drawmij's Instant Summons",
    level: 6,
    school: 'conjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma safira no valor de 1000 PO' },
    componentsText: 'V, S, M (uma safira no valor de 1000 PO)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: true,
    description:
      'Você marca um objeto de até 5 kg e escreve o nome dele na safira. Depois, quebrar a safira invoca o objeto para a sua mão no mesmo plano.',
    classes: [],
  },
  {
    id: 'eyebite',
    namePt: 'Olhar Maldito',
    nameEn: 'Eyebite',
    level: 6,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Seus olhos ficam negros. A cada turno, com uma ação, você mira uma criatura a até 18 m: ela faz salvaguarda de Sabedoria ou adormece, fica amedrontada ou adoecida (à sua escolha).',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'find-the-path',
    namePt: 'Encontrar o Caminho',
    nameEn: 'Find the Path',
    level: 6,
    school: 'divination',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'ferramentas de adivinhação no valor de 100 PO' },
    componentsText: 'V, S, M (ferramentas de adivinhação no valor de 100 PO)',
    duration: 'Concentração, até 1 dia',
    concentration: true,
    ritual: false,
    description:
      'Você descobre o caminho mais direto e curto até um local conhecido no mesmo plano e sabe quando o caminho vira ou termina; funciona mesmo em passagens enganosas.',
    classes: [],
  },
  {
    id: 'flesh-to-stone',
    namePt: 'Carne para Pedra',
    nameEn: 'Flesh to Stone',
    level: 6,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pouco de cal, água e terra' },
    componentsText: 'V, S, M (cal, água e terra)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura a até 18 m faz salvaguarda de Constituição ou fica impedida. Falhando em três salvaguardas, vira pedra permanentemente; passando em três, volta ao normal.',
    save: 'constitution',
    classes: [],
  },
  {
    id: 'forbiddance',
    namePt: 'Proibição',
    nameEn: 'Forbiddance',
    level: 6,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'água benta, incenso raro e pó de rubi no valor de 1000 PO, consumidos' },
    componentsText: 'V, S, M (água benta, incenso raro e pó de rubi de 1000 PO, consumidos)',
    duration: '1 dia',
    concentration: false,
    ritual: true,
    description:
      'Você protege uma área de até 3700 m²: criaturas escolhidas sofrem 5d10 de dano radiante ou necrótico ao entrar, e teleporte para dentro é bloqueado.',
    classes: [],
  },
  {
    id: 'globe-of-invulnerability',
    namePt: 'Globo de Invulnerabilidade',
    nameEn: 'Globe of Invulnerability',
    level: 6,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'sphere', sizeMeters: 3, note: 'origem em você' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma conta de vidro ou cristal claro' },
    componentsText: 'V, S, M (uma conta de vidro ou cristal claro)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma barreira imóvel e cintilante envolve você. Magias de 5º nível ou menos lançadas de fora não afetam quem está dentro do globo de 3 m de raio.',
    upcast: { note: 'Bloqueia magias de 1 nível acima por nível de espaço acima do 6º.' },
    classes: [],
  },
  {
    id: 'guards-and-wards',
    namePt: 'Guardas e Proteções',
    nameEn: 'Guards and Wards',
    level: 6,
    school: 'abjuration',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'incenso aceso, enxofre, óleo, barbante, sangue e uma haste de prata de 10 PO' },
    componentsText: 'V, S, M (incenso, enxofre, óleo, barbante, sangue e uma haste de prata de 10 PO)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Você protege um andar ou área: cria névoa, portas trancadas, escadas cobertas de teias, passagens falsas e pode colocar uma sugestão para escolher um caminho.',
    classes: [],
  },
  {
    id: 'harm',
    namePt: 'Ferimento',
    nameEn: 'Harm',
    level: 6,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura a até 18 m faz salvaguarda de Constituição ou sofre 14d6 de dano necrótico (metade se passar). Os PV dela não podem ficar abaixo de 1; se já tiver 1 PV devido a esta magia, é reduzida a 0.',
    save: 'constitution',
    damage: [{ count: 14, sides: 6, bonus: 0, type: 'Necrótico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'heal',
    namePt: 'Curar',
    nameEn: 'Heal',
    level: 6,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura visível a até 18 m recupera 70 pontos de vida e fica curada de cegueira, surdez e doenças. Não afeta constructos nem mortos-vivos.',
    healing: { count: 0, sides: 0, bonus: 70, type: null },
    upcast: { note: 'A cura aumenta em 10 por nível de espaço acima do 6º.' },
    classes: [],
  },
  {
    id: 'heroes-feast',
    namePt: 'Banquete de Heróis',
    nameEn: "Heroes' Feast",
    level: 6,
    school: 'conjuration',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma tigela incrustada de gemas no valor de 1000 PO, consumida' },
    componentsText: 'V, S, M (uma tigela incrustada de gemas de 1000 PO, consumida)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Um banquete aparece. Até doze criaturas que comem ganham 2d10 PV máximos adicionais, ficam curadas de doenças e venenos, imunes a veneno e amedrontadas, e têm vantagem em salvaguardas de Sabedoria por 24 h.',
    classes: [],
  },
  {
    id: 'magic-jar',
    namePt: 'Jarra Mágica',
    nameEn: 'Magic Jar',
    level: 6,
    school: 'necromancy',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gema, cristal ou relicário no valor de 100 PO' },
    componentsText: 'V, S, M (uma gema, cristal ou relicário de 100 PO)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: false,
    description:
      'Sua alma entra num recipiente e você pode possuir corpos de humanoides a até 30 m (salvaguarda de Carisma). Enquanto possuir alguém, seu corpo fica inconsciente e protegido.',
    save: 'charisma',
    classes: [],
  },
  {
    id: 'mass-suggestion',
    namePt: 'Sugestão em Massa',
    nameEn: 'Mass Suggestion',
    level: 6,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: true },
    material: { text: 'uma língua de cobra e um favo de mel' },
    componentsText: 'M (uma língua de cobra e um favo de mel)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Até doze criaturas à sua escolha a até 18 m fazem salvaguarda de Sabedoria ou seguem a sugestão que você fizer enquanto ela durar; a magia acaba para quem sofrer dano de você ou aliados.',
    save: 'wisdom',
    upcast: { note: 'A duração aumenta por nível de espaço acima do 6º (até 1 ano e 1 dia com 9º).' },
    classes: [],
  },
  {
    id: 'move-earth',
    namePt: 'Mover Terra',
    nameEn: 'Move Earth',
    level: 6,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'cube', sizeMeters: 12 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma lâmina de ferro e um saco de terra misturada' },
    componentsText: 'V, S, M (uma lâmina de ferro e um saco de terra misturada)',
    duration: 'Concentração, até 2 horas',
    concentration: true,
    ritual: false,
    description:
      'Você remodela terreno de terra, areia ou argila numa área de até 12 m de lado (profundidade depende do uso), podendo escavar valas, erguer colinas ou criar trincheiras lentamente.',
    classes: [],
  },
  {
    id: 'otilukes-freezing-sphere',
    namePt: 'Esfera Congelante de Otiluke',
    nameEn: "Otiluke's Freezing Sphere",
    level: 6,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '90 m',
    rangeKind: 'ranged',
    rangeMeters: 90,
    area: { shape: 'sphere', sizeMeters: 18 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pequena esfera de cristal' },
    componentsText: 'V, S, M (uma pequena esfera de cristal)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma esfera de frio explode num raio de 18 m. Cada criatura na área faz salvaguarda de Constituição ou sofre 10d6 de dano de frio (metade se passar). Você pode lançá-la à distância depois de conjurá-la.',
    save: 'constitution',
    damage: [{ count: 10, sides: 6, bonus: 0, type: 'Frio' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'ottos-irresistible-dance',
    namePt: 'Dança Irresistível de Otto',
    nameEn: "Otto's Irresistible Dance",
    level: 6,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura a até 9 m começa a dançar: ela faz salvaguarda de Sabedoria ou fica incapacitada, com deslocamento reduzido e desvantagem em Destreza. Ela pode repetir a salvaguarda a cada turno.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'planar-ally',
    namePt: 'Aliado Extraplanar',
    nameEn: 'Planar Ally',
    level: 6,
    school: 'conjuration',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você pede a uma entidade divina que envie um celestial, elemental ou corruptor para ajudá-lo. O mensageiro pede uma recompensa (em PO ou itens) para realizar a tarefa.',
    classes: [],
  },
  {
    id: 'programmed-illusion',
    namePt: 'Ilusão Programada',
    nameEn: 'Programmed Illusion',
    level: 6,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'cube', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de velo e pó de jade no valor de 25 PO' },
    componentsText: 'V, S, M (um pedaço de velo e pó de jade de 25 PO)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: false,
    description:
      'Você cria a ilusão de um objeto, criatura ou evento dentro de um cubo de 9 m, que se ativa sob uma condição que você definir. Após ativada, dura até 5 min e pode se repetir.',
    classes: [],
  },
  {
    id: 'sunbeam',
    namePt: 'Raio Solar',
    nameEn: 'Sunbeam',
    level: 6,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'line', sizeMeters: 18, note: '1,5 m de largura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma lupa' },
    componentsText: 'V, S, M (uma lupa)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Um feixe de luz brilhante de 18 m de comprimento e 1,5 m de largura emana de você. Cada criatura na área faz salvaguarda de Constituição ou sofre 6d8 de dano radiante e fica cega até o próximo turno.',
    save: 'constitution',
    damage: [{ count: 6, sides: 8, bonus: 0, type: 'Radiante' }],
    upcast: { note: 'Com espaço de 7º ou superior, você pode criar um feixe extra por nível acima do 6º.' },
    classes: [],
  },
  {
    id: 'transport-via-plants',
    namePt: 'Transporte por Plantas',
    nameEn: 'Transport via Plants',
    level: 6,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma planta Enorme ou maior e cria um portal ligado a outra planta da mesma espécie no mesmo plano, que você já tenha visto antes. O portal dura até o fim do seu próximo turno.',
    classes: [],
  },
  {
    id: 'true-seeing',
    namePt: 'Visão Verdadeira',
    nameEn: 'True Seeing',
    level: 6,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pó de cogumelo, açafrão e gordura, no valor de 25 PO, consumidos' },
    componentsText: 'V, S, M (pó de cogumelo, açafrão e gordura de 25 PO, consumidos)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura voluntária ganha visão verdadeira de 36 m: enxerga o invisível, o Etéreo, coisas e criaturas metamorfoseadas, e vê através de ilusões e escuridão mágica.',
    classes: [],
  },
  {
    id: 'wall-of-ice',
    namePt: 'Muralha de Gelo',
    nameEn: 'Wall of Ice',
    level: 6,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pequeno pedaço de quartzo' },
    componentsText: 'V, S, M (um pequeno pedaço de quartzo)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma parede de gelo surge (hemisfério de até 3 m de raio ou painéis de 3 m × 3 m). Ela bloqueia ataques e magias; se destruída, deixa ar frio que causa 5d6 de dano de frio a quem atravessar.',
    save: 'dexterity',
    damage: [{ count: 10, sides: 6, bonus: 0, type: 'Frio' }],
    upcast: { note: 'Os PV da muralha e o dano do ar frio aumentam por nível de espaço acima do 6º.' },
    classes: [],
  },
  {
    id: 'wall-of-thorns',
    namePt: 'Muralha de Espinhos',
    nameEn: 'Wall of Thorns',
    level: 6,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um punhado de espinhos' },
    componentsText: 'V, S, M (um punhado de espinhos)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma parede de espinhos emaranhados de 18 m de comprimento surge. Quem estiver na área faz salvaguarda de Destreza ou sofre 7d8 de dano perfurante (metade se passar); atravessá-la custa movimento e causa dano.',
    save: 'dexterity',
    damage: [{ count: 7, sides: 8, bonus: 0, type: 'Perfurante' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'wind-walk',
    namePt: 'Caminhar no Vento',
    nameEn: 'Wind Walk',
    level: 6,
    school: 'transmutation',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'fogo e água benta' },
    componentsText: 'V, S, M (fogo e água benta)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Até dez criaturas à sua escolha a até 9 m viram nuvens gasosas: ganham deslocamento de voo de 90 m, resistência a dano não mágico e podem voltar à forma normal com uma ação.',
    classes: [],
  },
  {
    id: 'word-of-recall',
    namePt: 'Palavra de Retorno',
    nameEn: 'Word of Recall',
    level: 6,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '1,5 m',
    rangeKind: 'ranged',
    rangeMeters: 1.5,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você e até cinco criaturas voluntárias a até 1,5 m se teleportam para um santuário que você preparou previamente, no mesmo plano.',
    classes: [],
  },
];
