import type { Spell } from '../types.js';

/**
 * Magias de 4º nível do PHB 2014 (35). Ordem alfabética pelo nome em inglês.
 * `classes` fica VAZIO até o Prompt 6.2.
 */
export const LEVEL_4: readonly Spell[] = [
  {
    id: 'arcane-eye',
    namePt: 'Olho Arcano',
    nameEn: 'Arcane Eye',
    level: 4,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pouco de pelo de morcego' },
    componentsText: 'V, S, M (um pouco de pelo de morcego)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você cria um olho invisível que flutua e enxerga em todas as direções. Com uma ação, você o move até 9 m; ele não atravessa barreiras sólidas de mais de 30 cm.',
    classes: [],
  },
  {
    id: 'aura-of-life',
    namePt: 'Aura de Vida',
    nameEn: 'Aura of Life',
    level: 4,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma aura de energia revigorante irradia de você. Criaturas não hostis a até 9 m têm resistência a dano necrótico e os PV máximos delas não podem ser reduzidos.',
    classes: [],
  },
  {
    id: 'aura-of-purity',
    namePt: 'Aura de Pureza',
    nameEn: 'Aura of Purity',
    level: 4,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma aura purificadora irradia de você. Criaturas não hostis a até 9 m têm vantagem em salvaguardas contra doenças e veneno e resistência a dano de veneno.',
    classes: [],
  },
  {
    id: 'banishment',
    namePt: 'Banimento',
    nameEn: 'Banishment',
    level: 4,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um item que desagrade o alvo' },
    componentsText: 'V, S, M (um item que desagrade o alvo)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura a até 18 m faz salvaguarda de Carisma ou é enviada a um semiplano inofensivo. Se a magia durar 1 minuto, a criatura é banida para sempre (se não for do plano atual).',
    save: 'charisma',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'blight',
    namePt: 'Murchar',
    nameEn: 'Blight',
    level: 4,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura a até 9 m faz salvaguarda de Constituição ou sofre 8d6 de dano necrótico (metade se passar). Plantas e mortos-vivos têm desvantagem e plantas/criaturas de planta sofrem o máximo de dano.',
    save: 'constitution',
    damage: [{ count: 8, sides: 6, bonus: 0, type: 'Necrótico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'compulsion',
    namePt: 'Compulsão',
    nameEn: 'Compulsion',
    level: 4,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Criaturas à sua escolha a até 9 m fazem salvaguarda de Sabedoria ou devem usar o deslocamento para se mover na direção que você indicar em cada turno; você pode mudar a direção a cada turno.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'confusion',
    namePt: 'Confusão',
    nameEn: 'Confusion',
    level: 4,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    area: { shape: 'sphere', sizeMeters: 3 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'três cascas de noz' },
    componentsText: 'V, S, M (três cascas de noz)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Cada criatura numa esfera de 3 m de raio faz salvaguarda de Sabedoria ou fica confusa: rola 1d10 a cada turno para determinar se age normalmente, fica atordoada, ataca aleatoriamente, se move aleatoriamente ou fica parada.',
    save: 'wisdom',
    upcast: { note: 'O raio aumenta 1,5 m por nível de espaço acima do 4º.' },
    classes: [],
  },
  {
    id: 'conjure-minor-elementals',
    namePt: 'Convocar Elementais Menores',
    nameEn: 'Conjure Minor Elementals',
    level: 4,
    school: 'conjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você invoca elementais. Escolha: um de NC 2, dois de NC 1, quatro de NC 1/2 ou oito de NC 1/4. Eles são amigáveis e obedecem às suas ordens.',
    upcast: { note: 'O dobro de criaturas por nível de espaço acima do 4º.' },
    classes: [],
  },
  {
    id: 'conjure-woodland-beings',
    namePt: 'Convocar Seres da Floresta',
    nameEn: 'Conjure Woodland Beings',
    level: 4,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma baga de azevinho por criatura invocada' },
    componentsText: 'V, S, M (uma baga de azevinho)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você invoca criaturas feéricas. Escolha: uma de NC 2, duas de NC 1, quatro de NC 1/2 ou oito de NC 1/4. Elas obedecem às suas ordens.',
    upcast: { note: 'O dobro de criaturas por nível de espaço acima do 4º.' },
    classes: [],
  },
  {
    id: 'control-water',
    namePt: 'Controlar Água',
    nameEn: 'Control Water',
    level: 4,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '90 m',
    rangeKind: 'ranged',
    rangeMeters: 90,
    area: { shape: 'cube', sizeMeters: 30 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gota de água e uma pitada de poeira' },
    componentsText: 'V, S, M (uma gota de água e uma pitada de poeira)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Você controla água num cubo de 30 m: pode inundar, separar as águas, redirecionar o fluxo ou criar um redemoinho (salvaguarda de Força).',
    save: 'strength',
    classes: [],
  },
  {
    id: 'death-ward',
    namePt: 'Proteção contra a Morte',
    nameEn: 'Death Ward',
    level: 4,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura que você toca é protegida da morte: a primeira vez que cair a 0 PV, ela fica com 1 PV em vez disso; a primeira vez que seria morta instantaneamente, a magia evita isso.',
    classes: [],
  },
  {
    id: 'dimension-door',
    namePt: 'Porta Dimensional',
    nameEn: 'Dimension Door',
    level: 4,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '150 m',
    rangeKind: 'ranged',
    rangeMeters: 150,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você se teleporta para um ponto a até 150 m, junto de uma criatura voluntária (do seu tamanho ou menor) que esteja a até 1,5 m. Se o destino for ocupado, você e quem o acompanha sofrem 4d6 de dano de força.',
    classes: [],
  },
  {
    id: 'divination',
    namePt: 'Adivinhação',
    nameEn: 'Divination',
    level: 4,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'incenso e uma oferenda no valor de 25 PO, consumidos' },
    componentsText: 'V, S, M (incenso e uma oferenda no valor de 25 PO, consumidos)',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    description:
      'Você faz uma pergunta sobre um evento dos próximos 7 dias e recebe uma resposta verídica (embora possa ser enigmática), vinda de uma entidade divina.',
    classes: [],
  },
  {
    id: 'dominate-beast',
    namePt: 'Dominar Besta',
    nameEn: 'Dominate Beast',
    level: 4,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma besta a até 18 m faz salvaguarda de Sabedoria ou fica enfeitiçada e sob seu controle enquanto durar; você pode usar uma ação para comandar o que ela faz. Tem vantagem se você estiver lutando com ela.',
    save: 'wisdom',
    upcast: { note: 'Com espaços de 5º/6º dura até 10 min; de 7º ou maior, até 1 hora.' },
    classes: [],
  },
  {
    id: 'evards-black-tentacles',
    namePt: 'Tentáculos Negros de Evard',
    nameEn: "Evard's Black Tentacles",
    level: 4,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    area: { shape: 'cube', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de tentáculo' },
    componentsText: 'V, S, M (um pedaço de tentáculo)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Tentáculos negros preenchem um quadrado de 6 m. Cada criatura na área faz salvaguarda de Destreza ou fica impedida e sofre 3d6 de dano de concussão no início de cada turno; quem falhar pode repetir a salvaguarda.',
    save: 'dexterity',
    damage: [{ count: 3, sides: 6, bonus: 0, type: 'Concussão' }],
    classes: [],
  },
  {
    id: 'fabricate',
    namePt: 'Fabricar',
    nameEn: 'Fabricate',
    level: 4,
    school: 'transmutation',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você converte matéria-prima em um produto acabado. Com materiais suficientes, fabrica um objeto Grande ou menor de metal, pedra, madeira ou fibras.',
    classes: [],
  },
  {
    id: 'fire-shield',
    namePt: 'Escudo de Fogo',
    nameEn: 'Fire Shield',
    level: 4,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pouco de fósforo ou um vaga-lume' },
    componentsText: 'V, S, M (um pouco de fósforo ou um vaga-lume)',
    duration: '10 minutos',
    concentration: false,
    ritual: false,
    description:
      'Chamas quentes ou frias envolvem você, emitindo luz. Você escolhe resistência a dano de fogo ou de frio e, quando uma criatura o acerta corpo a corpo, ela sofre 2d8 de dano do tipo oposto.',
    damage: [{ count: 2, sides: 8, bonus: 0, type: null }],
    classes: [],
  },
  {
    id: 'freedom-of-movement',
    namePt: 'Liberdade de Movimento',
    nameEn: 'Freedom of Movement',
    level: 4,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma tira de couro amarrada ao braço' },
    componentsText: 'V, S, M (uma tira de couro amarrada ao braço)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura que você toca ignora terreno difícil, magias não a deixam impedida nem paralisada, e gastar 1,5 m de movimento a liberta de agarrões e da condição apanhado.',
    classes: [],
  },
  {
    id: 'giant-insect',
    namePt: 'Inseto Gigante',
    nameEn: 'Giant Insect',
    level: 4,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Você transforma até dez centopeias, três aranhas, cinco vespas ou um escorpião em versões gigantes por 10 min, que obedecem às suas ordens verbais.',
    upcast: { note: 'Com espaço de 5º ou superior, invoca o dobro de insetos.' },
    classes: [],
  },
  {
    id: 'grasping-vine',
    namePt: 'Vinha Agarrante',
    nameEn: 'Grasping Vine',
    level: 4,
    school: 'conjuration',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma vinha brota de uma superfície num ponto a até 9 m. Com uma ação bônus, você a faz agarrar uma criatura a até 9 m dela: o alvo faz salvaguarda de Destreza ou é puxado 6 m na direção da vinha.',
    save: 'dexterity',
    classes: [],
  },
  {
    id: 'greater-invisibility',
    namePt: 'Invisibilidade Maior',
    nameEn: 'Greater Invisibility',
    level: 4,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura que você toca fica invisível enquanto a magia durar, mesmo se atacar ou lançar magias.',
    classes: [],
  },
  {
    id: 'guardian-of-faith',
    namePt: 'Guardião da Fé',
    nameEn: 'Guardian of Faith',
    level: 4,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Um guardião espectral Grande aparece e guarda uma área. Uma criatura hostil que entre a até 3 m dele faz salvaguarda de Destreza ou sofre 20 de dano radiante; ele causa no máximo 60 de dano antes de desaparecer.',
    save: 'dexterity',
    damage: [{ count: 0, sides: 0, bonus: 20, type: 'Radiante' }],
    classes: [],
  },
  {
    id: 'hallucinatory-terrain',
    namePt: 'Terreno Alucinatório',
    nameEn: 'Hallucinatory Terrain',
    level: 4,
    school: 'illusion',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: '90 m',
    rangeKind: 'ranged',
    rangeMeters: 90,
    area: { shape: 'cube', sizeMeters: 45 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pedra, um graveto e um pedaço de planta verde' },
    componentsText: 'V, S, M (uma pedra, um graveto e um pedaço de planta verde)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Você faz um terreno natural numa área de 45 m parecer, soar e cheirar como outro tipo de terreno natural, escondendo estradas, poços ou acampamentos.',
    classes: [],
  },
  {
    id: 'ice-storm',
    namePt: 'Tempestade de Gelo',
    nameEn: 'Ice Storm',
    level: 4,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '90 m',
    rangeKind: 'ranged',
    rangeMeters: 90,
    area: { shape: 'cylinder', sizeMeters: 6, note: 'raio de 6 m, 12 m de altura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de pó e algumas gotas de água' },
    componentsText: 'V, S, M (uma pitada de pó e algumas gotas de água)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Granizo cai num cilindro de 6 m de raio e 12 m de altura. Cada criatura na área faz salvaguarda de Destreza: se falhar, sofre 2d8 de dano de concussão e 4d6 de dano de frio; se passar, metade. O chão vira terreno difícil.',
    save: 'dexterity',
    damage: [
      { count: 2, sides: 8, bonus: 0, type: 'Concussão' },
      { count: 4, sides: 6, bonus: 0, type: 'Frio' },
    ],
    upcast: { extraDicePerSlot: 1, note: 'Some 1d8 ao dano de concussão por nível acima do 4º.' },
    classes: [],
  },
  {
    id: 'leomunds-secret-chest',
    namePt: 'Baú Secreto de Leomund',
    nameEn: "Leomund's Secret Chest",
    level: 4,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um baú especial de 5000 PO e uma réplica de 50 PO' },
    componentsText: 'V, S, M (um baú especial de 5000 PO e uma réplica de 50 PO)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você esconde um baú de 0,9 m × 0,6 m × 0,6 m no Plano Etéreo. Com uma ação e a réplica, você o invoca ou o devolve; após 60 dias é possível perdê-lo para sempre.',
    classes: [],
  },
  {
    id: 'locate-creature',
    namePt: 'Localizar Criatura',
    nameEn: 'Locate Creature',
    level: 4,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pouco de pelo de um cão de caça' },
    componentsText: 'V, S, M (um pouco de pelo de um cão de caça)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Descreva uma criatura familiar: você sente a direção e a distância dela a até 300 m. Água corrente bloqueia a magia.',
    classes: [],
  },
  {
    id: 'mordenkainens-faithful-hound',
    namePt: 'Cão Fiel de Mordenkainen',
    nameEn: "Mordenkainen's Faithful Hound",
    level: 4,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um apito de prata, um osso e um fio' },
    componentsText: 'V, S, M (um apito de prata, um osso e um fio)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Um cão fantasma invisível aparece. Ele late quando uma criatura se aproxima a até 9 m (sem ser você e aliados) e morde a criatura mais próxima, causando 4d8 de dano perfurante (sem errar).',
    damage: [{ count: 4, sides: 8, bonus: 0, type: 'Perfurante' }],
    classes: [],
  },
  {
    id: 'mordenkainens-private-sanctum',
    namePt: 'Santuário Particular de Mordenkainen',
    nameEn: "Mordenkainen's Private Sanctum",
    level: 4,
    school: 'abjuration',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'cube', sizeMeters: 30 },
    components: { verbal: true, somatic: true, material: true },
    material: {
      text: 'uma lâmina fina de chumbo, um pedaço de vidro opaco, um chumaço de algodão e crisólita em pó',
    },
    componentsText: 'V, S, M (chumbo, vidro opaco, algodão e crisólita em pó)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Você protege uma área de 30 m de lado: o som não atravessa as bordas, o interior não pode ser observado por sensores mágicos, adivinhações são bloqueadas e criaturas não podem se teleportar para dentro.',
    classes: [],
  },
  {
    id: 'otilukes-resilient-sphere',
    namePt: 'Esfera Resiliente de Otiluke',
    nameEn: "Otiluke's Resilient Sphere",
    level: 4,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    area: { shape: 'sphere', sizeMeters: 3 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço hemisférico de cristal e goma arábica' },
    componentsText: 'V, S, M (um pedaço hemisférico de cristal e goma arábica)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma esfera de energia de 3 m de raio aprisiona uma criatura ou objeto. Uma criatura não voluntária faz salvaguarda de Destreza; nada atravessa a esfera, nem de dentro nem de fora.',
    save: 'dexterity',
    classes: [],
  },
  {
    id: 'phantasmal-killer',
    namePt: 'Assassino Fantasmagórico',
    nameEn: 'Phantasmal Killer',
    level: 4,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você acessa os medos de uma criatura a até 36 m. Se ela falhar numa salvaguarda de Sabedoria, fica amedrontada e, no fim de cada turno, faz outra salvaguarda ou sofre 4d10 de dano psíquico (metade se passar).',
    save: 'wisdom',
    damage: [{ count: 4, sides: 10, bonus: 0, type: 'Psíquico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'polymorph',
    namePt: 'Polimorfia',
    nameEn: 'Polymorph',
    level: 4,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um casulo de lagarta' },
    componentsText: 'V, S, M (um casulo de lagarta)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura a até 18 m que possa ver faz salvaguarda de Sabedoria ou se transforma numa besta com NC igual ou inferior ao nível dela. A transformação dura enquanto a magia durar.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'staggering-smite',
    namePt: 'Golpe Atordoante',
    nameEn: 'Staggering Smite',
    level: 4,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar com uma arma, o alvo sofre 4d6 de dano psíquico adicional e faz salvaguarda de Sabedoria ou tem desvantagem em ataques e testes de atributo e não pode fazer reações até o fim do próximo turno dele.',
    save: 'wisdom',
    damage: [{ count: 4, sides: 6, bonus: 0, type: 'Psíquico' }],
    classes: [],
  },
  {
    id: 'stone-shape',
    namePt: 'Moldar Pedra',
    nameEn: 'Stone Shape',
    level: 4,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'argila mole' },
    componentsText: 'V, S, M (argila mole)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma pedra de tamanho Médio ou menor (ou uma seção de pedra) e a molda na forma que desejar, podendo criar passagens, portas ou fechaduras.',
    classes: [],
  },
  {
    id: 'stoneskin',
    namePt: 'Pele de Pedra',
    nameEn: 'Stoneskin',
    level: 4,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'granito e pó de diamante no valor de 100 PO, consumidos' },
    componentsText: 'V, S, M (granito e pó de diamante no valor de 100 PO, consumidos)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'A pele de uma criatura voluntária que você toca endurece: ela ganha resistência a dano de concussão, perfurante e cortante não mágico.',
    classes: [],
  },
  {
    id: 'wall-of-fire',
    namePt: 'Muralha de Fogo',
    nameEn: 'Wall of Fire',
    level: 4,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'line', sizeMeters: 18, note: 'ou anel de 6 m de raio, 3 m de altura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pequeno pedaço de fósforo' },
    componentsText: 'V, S, M (um pequeno pedaço de fósforo)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma muralha de fogo de 18 m de comprimento ou anel de 6 m de raio surge. Cada criatura na área faz salvaguarda de Destreza ou sofre 5d8 de dano de fogo (metade se passar); um lado da muralha queima mais forte. Ao conjurar, você escolhe qual lado é o quente.',
    save: 'dexterity',
    damage: [{ count: 5, sides: 8, bonus: 0, type: 'Fogo' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
];
