import type { Spell } from '../types.js';

/**
 * Magias de 3º nível do PHB 2014 (50). Ordem alfabética pelo nome em inglês.
 * `classes` fica VAZIO até o Prompt 6.2.
 */
export const LEVEL_3: readonly Spell[] = [
  {
    id: 'animate-dead',
    namePt: 'Animar Mortos',
    nameEn: 'Animate Dead',
    level: 3,
    school: 'necromancy',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gota de sangue, um pedaço de carne e uma pitada de pó de osso' },
    componentsText: 'V, S, M (uma gota de sangue, um pedaço de carne e uma pitada de pó de osso)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você anima um esqueleto ou zumbi a partir de um monte de ossos ou cadáver. O morto-vivo obedece a comandos seus por 24 h; para renovar o controle, é preciso conjurar de novo.',
    upcast: { extraTargetsPerSlot: 2 },
    classes: [],
  },
  {
    id: 'aura-of-vitality',
    namePt: 'Aura de Vitalidade',
    nameEn: 'Aura of Vitality',
    level: 3,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma aura de energia curativa irradia de você. Com uma ação bônus, você pode fazer uma criatura a até 9 m recuperar 2d6 pontos de vida.',
    classes: [],
  },
  {
    id: 'beacon-of-hope',
    namePt: 'Farol de Esperança',
    nameEn: 'Beacon of Hope',
    level: 3,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Criaturas à sua escolha a até 9 m têm vantagem em salvaguardas contra morte e em testes de Sabedoria, e recebem o máximo de cura de qualquer magia que as cure.',
    classes: [],
  },
  {
    id: 'bestow-curse',
    namePt: 'Conceder Maldição',
    nameEn: 'Bestow Curse',
    level: 3,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Você toca uma criatura e ela faz salvaguarda de Sabedoria ou recebe uma maldição: desvantagem em testes de um atributo, desvantagem em ataques contra você, obrigação de fazer salvaguarda de Sabedoria ou perder a ação, ou sofrer 1d8 de dano necrótico extra seu.',
    save: 'wisdom',
    upcast: { note: 'Com espaço de 5º/6º nível dura até 8 h; de 7º ou maior, até 24 h e até ser dissipada com 9º.' },
    classes: [],
  },
  {
    id: 'blinding-smite',
    namePt: 'Golpe Cegante',
    nameEn: 'Blinding Smite',
    level: 3,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar com uma arma, o alvo sofre 3d8 de dano radiante adicional e faz salvaguarda de Constituição ou fica cego até o fim da magia.',
    save: 'constitution',
    damage: [{ count: 3, sides: 8, bonus: 0, type: 'Radiante' }],
    classes: [],
  },
  {
    id: 'blink',
    namePt: 'Piscar',
    nameEn: 'Blink',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Você pisca entre o Plano Material e o Etéreo. No fim de cada um dos seus turnos, role 1d20: com 11 ou mais você some para o Etéreo e reaparece a até 3 m no início do próximo turno.',
    classes: [],
  },
  {
    id: 'call-lightning',
    namePt: 'Convocar Relâmpagos',
    nameEn: 'Call Lightning',
    level: 3,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'cylinder', sizeMeters: 1.5, note: '1,5 m de raio, 18 m de altura' },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma nuvem de tempestade se forma. Com uma ação, você pode fazer um relâmpago cair num ponto a até 36 m: cada criatura na área faz salvaguarda de Destreza ou sofre 3d10 de dano elétrico (metade se passar).',
    save: 'dexterity',
    damage: [{ count: 3, sides: 10, bonus: 0, type: 'Elétrico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'clairvoyance',
    namePt: 'Clarividência',
    nameEn: 'Clairvoyance',
    level: 3,
    school: 'divination',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: '1,5 km',
    rangeKind: 'ranged',
    rangeMeters: 1500,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um foco no valor de 100 PO' },
    componentsText: 'V, S, M (um foco no valor de 100 PO)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Você cria um sensor invisível num local familiar ou óbvio a até 1,5 km, podendo ver ou ouvir (à sua escolha) através dele. Com uma ação, você pode alternar entre ver e ouvir.',
    classes: [],
  },
  {
    id: 'conjure-animals',
    namePt: 'Convocar Animais',
    nameEn: 'Conjure Animals',
    level: 3,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você invoca espíritos feéricos que assumem formas de bestas. Escolha: uma besta de NC 2, duas de NC 1, quatro de NC 1/2 ou oito de NC 1/4. As bestas são leais e amigas.',
    upcast: { note: 'O dobro de criaturas por nível de espaço acima do 3º.' },
    classes: [],
  },
  {
    id: 'conjure-barrage',
    namePt: 'Barragem de Conjuração',
    nameEn: 'Conjure Barrage',
    level: 3,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'cone', sizeMeters: 18 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma munição ou arma de arremesso' },
    componentsText: 'V, S, M (uma munição ou arma de arremesso)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você brande uma arma e uma barragem de cópias dela varre um cone de 18 m. Cada criatura na área faz salvaguarda de Destreza ou sofre 3d8 de dano do tipo da arma (metade se passar).',
    save: 'dexterity',
    damage: [{ count: 3, sides: 8, bonus: 0, type: null }],
    classes: [],
  },
  {
    id: 'counterspell',
    namePt: 'Contramágica',
    nameEn: 'Counterspell',
    level: 3,
    school: 'abjuration',
    castingTime: '1 reação*',
    castingTimeKind: 'reaction',
    reactionTrigger: 'quando uma criatura a até 18 m que você possa ver conjura uma magia',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: false, somatic: true, material: false },
    componentsText: 'S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você tenta interromper uma criatura conjurando. Se a magia dela for de 3º nível ou menos, falha automaticamente; se for de nível maior, você faz um teste de atributo de conjuração (CD 10 + nível da magia).',
    classes: [],
  },
  {
    id: 'create-food-and-water',
    namePt: 'Criar Comida e Água',
    nameEn: 'Create Food and Water',
    level: 3,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você cria 20 kg de comida saborosa e 120 litros de água doce, suficientes para sustentar até quinze humanoides por 24 h. A comida estraga se não for consumida a tempo.',
    classes: [],
  },
  {
    id: 'crusaders-mantle',
    namePt: 'Manto do Cruzado',
    nameEn: "Crusader's Mantle",
    level: 3,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma aura sagrada irradia de você. Enquanto durar, cada criatura não hostil a até 9 m de você causa 1d4 de dano radiante adicional em ataques de arma.',
    classes: [],
  },
  {
    id: 'daylight',
    namePt: 'Luz do Dia',
    nameEn: 'Daylight',
    level: 3,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'sphere', sizeMeters: 18 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Luz plena de 18 m de raio irrompe de um ponto ou objeto a até 18 m. Se o local já for mágico de escuridão, a magia anula a escuridão de nível igual ou inferior.',
    classes: [],
  },
  {
    id: 'dispel-magic',
    namePt: 'Dissipar Magia',
    nameEn: 'Dispel Magic',
    level: 3,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Escolha uma criatura, objeto ou efeito mágico a até 36 m. Magias de 3º nível ou menor acabam; para as de nível maior, faça um teste de atributo de conjuração (CD 10 + nível da magia).',
    upcast: { note: 'Dissipa automaticamente magias de nível igual ou inferior ao espaço usado.' },
    classes: [],
  },
  {
    id: 'elemental-weapon',
    namePt: 'Arma Elemental',
    nameEn: 'Elemental Weapon',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma arma não mágica que você toca ganha +1 nos ataques e 1d4 de dano de um tipo à sua escolha (ácido, frio, fogo, elétrico ou trovão).',
    damage: [{ count: 1, sides: 4, bonus: 0, type: null }],
    upcast: { note: 'O bônus de ataque/dano e os dados elementais aumentam com espaços de 5º/6º e 7º ou superior.' },
    classes: [],
  },
  {
    id: 'fear',
    namePt: 'Medo',
    nameEn: 'Fear',
    level: 3,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'cone', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pena branca ou o coração de uma galinha' },
    componentsText: 'V, S, M (uma pena branca ou o coração de uma galinha)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma imagem aterrorizante preenche um cone de 9 m. Cada criatura na área faz salvaguarda de Sabedoria ou larga o que segura e fica amedrontada, fugindo de você enquanto a magia durar.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'feign-death',
    namePt: 'Fingir de Morto',
    nameEn: 'Feign Death',
    level: 3,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma moeda de cobre colocada sobre os olhos do alvo' },
    componentsText: 'V, S, M (uma moeda de cobre)',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    description:
      'Você toca uma criatura voluntária e ela fica paralisada, com aparência de morta; fica cega e não pode se mover nem falar, e dano não a mata de imediato.',
    classes: [],
  },
  {
    id: 'fireball',
    namePt: 'Bola de Fogo',
    nameEn: 'Fireball',
    level: 3,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma bolinha de guano de morcego e enxofre' },
    componentsText: 'V, S, M (uma bolinha de guano de morcego e enxofre)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Um clarão de fogo explode numa esfera de 6 m de raio num ponto a até 45 m. Cada criatura na área faz salvaguarda de Destreza: se falhar, sofre 8d6 de dano de fogo, ou metade se passar. O fogo contorna cantos e incendeia objetos.',
    save: 'dexterity',
    damage: [{ count: 8, sides: 6, bonus: 0, type: 'Fogo' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'fly',
    namePt: 'Voar',
    nameEn: 'Fly',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pena de asa' },
    componentsText: 'V, S, M (uma pena de asa)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura voluntária que você toca ganha deslocamento de voo de 18 m por 10 min. Quando a magia acaba, se ainda estiver no ar, cai.',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'gaseous-form',
    namePt: 'Forma Gasosa',
    nameEn: 'Gaseous Form',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de gaze e um pouco de fumaça' },
    componentsText: 'V, S, M (um pedaço de gaze e um pouco de fumaça)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura voluntária vira névoa: ganha resistência a dano não mágico, vantagem em Força/Destreza/Constituição, deslocamento de voo de 3 m e pode atravessar frestas.',
    classes: [],
  },
  {
    id: 'glyph-of-warding',
    namePt: 'Glifo de Proteção',
    nameEn: 'Glyph of Warding',
    level: 3,
    school: 'abjuration',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'incenso e pó de diamante no valor de 200 PO, consumidos' },
    componentsText: 'V, S, M (incenso e pó de diamante no valor de 200 PO, consumidos)',
    duration: 'Até ser dissipada ou acionada',
    concentration: false,
    ritual: false,
    description:
      'Você inscreve um glifo que detona uma magia explosiva (raio de 6 m, 5d8 de ácido/frio/fogo/elétrico/trovão) ou guarda uma magia de até 3º nível, quando a condição que você definir ocorrer.',
    upcast: { extraDicePerSlot: 1, note: 'O dano do glifo explosivo aumenta 1d8 por nível acima do 3º.' },
    classes: [],
  },
  {
    id: 'haste',
    namePt: 'Acelerar',
    nameEn: 'Haste',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma raspagem de raiz de alcaçuz' },
    componentsText: 'V, S, M (uma raspagem de raiz de alcaçuz)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura voluntária a até 9 m fica acelerada: velocidade dobrada, +2 de CA, vantagem em Destreza e uma ação adicional limitada (atacar, Correr, Desengajar, Esconder-se ou Usar um Objeto). Ao fim, ela fica paralisada por 1 rodada.',
    classes: [],
  },
  {
    id: 'hunger-of-hadar',
    namePt: 'Fome de Hadar',
    nameEn: 'Hunger of Hadar',
    level: 3,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um tentáculo de polvo em conserva' },
    componentsText: 'V, S, M (um tentáculo de polvo em conserva)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma esfera de escuridão e frio de 6 m de raio se abre. Criaturas dentro ficam cegas e, no início do turno, sofrem 2d6 de dano de frio; quem terminar o turno ali faz salvaguarda de Destreza ou sofre 2d6 de dano de ácido.',
    save: 'dexterity',
    damage: [
      { count: 2, sides: 6, bonus: 0, type: 'Frio' },
      { count: 2, sides: 6, bonus: 0, type: 'Ácido' },
    ],
    classes: [],
  },
  {
    id: 'hypnotic-pattern',
    namePt: 'Padrão Hipnótico',
    nameEn: 'Hypnotic Pattern',
    level: 3,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'cube', sizeMeters: 9 },
    components: { verbal: false, somatic: true, material: true },
    material: { text: 'um incenso aceso ou um cristal que refrata luz' },
    componentsText: 'S, M (um incenso aceso ou um cristal que refrata luz)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Um padrão de cores gira num cubo de 9 m. Cada criatura na área que possa ver o padrão faz salvaguarda de Sabedoria ou fica enfeitiçada, com deslocamento 0 e incapacitada, até sofrer dano ou alguém sacudi-la.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'leomunds-tiny-hut',
    namePt: 'Cabana Minúscula de Leomund',
    nameEn: "Leomund's Tiny Hut",
    level: 3,
    school: 'evocation',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'sphere', sizeMeters: 3, note: 'hemisfério de 3 m de raio' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pequena conta de cristal' },
    componentsText: 'V, S, M (uma pequena conta de cristal)',
    duration: '8 horas',
    concentration: false,
    ritual: true,
    description:
      'Um domo imóvel de 3 m de raio surge ao seu redor. Criaturas e objetos escolhidos podem passar livremente; magias e efeitos de fora não atravessam, e o interior é confortável e seco.',
    classes: [],
  },
  {
    id: 'lightning-arrow',
    namePt: 'Flecha de Relâmpago',
    nameEn: 'Lightning Arrow',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar com um ataque à distância, a munição vira um relâmpago: o alvo sofre 4d8 de dano elétrico (metade numa salvaguarda de Destreza) e cada criatura a até 3 m dele faz a mesma salvaguarda ou sofre 2d8 de dano elétrico.',
    save: 'dexterity',
    damage: [{ count: 4, sides: 8, bonus: 0, type: 'Elétrico' }],
    upcast: { note: 'Some 1d8 ao dano principal por nível de espaço acima do 3º.' },
    classes: [],
  },
  {
    id: 'lightning-bolt',
    namePt: 'Raio',
    nameEn: 'Lightning Bolt',
    level: 3,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'line', sizeMeters: 30, note: '1,5 m de largura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pouco de pelo e uma haste de vidro' },
    componentsText: 'V, S, M (um pouco de pelo e uma haste de vidro)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Um relâmpago sai de você numa linha de 30 m de comprimento e 1,5 m de largura. Cada criatura na linha faz salvaguarda de Destreza ou sofre 8d6 de dano elétrico (metade se passar); objetos inflamáveis acendem.',
    save: 'dexterity',
    damage: [{ count: 8, sides: 6, bonus: 0, type: 'Elétrico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'magic-circle',
    namePt: 'Círculo Mágico',
    nameEn: 'Magic Circle',
    level: 3,
    school: 'abjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    area: { shape: 'cylinder', sizeMeters: 3, note: 'raio de 3 m, 6 m de altura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'água benta ou prata e ferro em pó no valor de 100 PO, consumidos' },
    componentsText: 'V, S, M (água benta ou prata e ferro em pó no valor de 100 PO, consumidos)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Um cilindro de 3 m de raio e 6 m de altura protege uma área contra um tipo de criatura (celestial, corruptor, elemental, fada, imundície ou morto-vivo): tais criaturas não podem entrar, encantar ou amedrontar quem está dentro.',
    upcast: { note: 'O raio aumenta 3 m e a duração dobra por nível de espaço acima do 3º.' },
    classes: [],
  },
  {
    id: 'major-image',
    namePt: 'Imagem Maior',
    nameEn: 'Major Image',
    level: 3,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'cube', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de velo' },
    componentsText: 'V, S, M (um pedaço de velo)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Você cria a imagem de um objeto, criatura ou fenômeno — com som, cheiro e temperatura — num cubo de 6 m. Com uma ação, você pode movê-la; interagir com ela revela a ilusão.',
    upcast: { note: 'Com espaço de 6º ou superior, dura até ser dissipada e não exige concentração.' },
    classes: [],
  },
  {
    id: 'mass-healing-word',
    namePt: 'Palavra Curativa em Massa',
    nameEn: 'Mass Healing Word',
    level: 3,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Até seis criaturas à sua escolha visíveis a até 18 m recuperam 1d4 + o seu modificador de atributo de conjuração em pontos de vida cada. Não afeta mortos-vivos nem constructos.',
    healing: { count: 1, sides: 4, bonus: 0, type: null },
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'meld-into-stone',
    namePt: 'Fundir-se à Pedra',
    nameEn: 'Meld into Stone',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '8 horas',
    concentration: false,
    ritual: true,
    description:
      'Você entra numa superfície de pedra grande o bastante para o seu corpo, ficando escondido por 8 h. Enquanto imerso, não vê o exterior e só percebe como o som chega à pedra.',
    classes: [],
  },
  {
    id: 'nondetection',
    namePt: 'Não Detecção',
    nameEn: 'Nondetection',
    level: 3,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de pó de diamante no valor de 25 PO, consumida' },
    componentsText: 'V, S, M (uma pitada de pó de diamante no valor de 25 PO, consumida)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Você esconde de magias de adivinhação uma criatura, um lugar ou um objeto que toque (um ponto no espaço também vale).',
    classes: [],
  },
  {
    id: 'phantom-steed',
    namePt: 'Corcel Fantasma',
    nameEn: 'Phantom Steed',
    level: 3,
    school: 'illusion',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    description:
      'Uma criatura quase real semelhante a um cavalo surge no chão. Ela tem deslocamento de 30 m e pode ser montada por 1 h; não ataca nem pode ser ferida.',
    classes: [],
  },
  {
    id: 'plant-growth',
    namePt: 'Crescimento de Plantas',
    nameEn: 'Plant Growth',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação ou 8 horas',
    castingTimeKind: 'special',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Com 1 ação, plantas num raio de 30 m ficam densas (terreno difícil para não mágicos). Com 8 h, todas as plantas de um raio de 750 m ficam férteis por 1 ano.',
    classes: [],
  },
  {
    id: 'protection-from-energy',
    namePt: 'Proteção contra Energia',
    nameEn: 'Protection from Energy',
    level: 3,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura voluntária que você toca ganha resistência a um tipo de dano à sua escolha: ácido, frio, fogo, elétrico ou trovão.',
    classes: [],
  },
  {
    id: 'remove-curse',
    namePt: 'Remover Maldição',
    nameEn: 'Remove Curse',
    level: 3,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Ao tocar uma criatura ou objeto, todas as maldições que os afetam acabam. Se o item for amaldiçoado, a magia quebra o vínculo, permitindo descartá-lo.',
    classes: [],
  },
  {
    id: 'revivify',
    namePt: 'Revivificar',
    nameEn: 'Revivify',
    level: 3,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'diamantes no valor de 300 PO, consumidos' },
    componentsText: 'V, S, M (diamantes no valor de 300 PO, consumidos)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma criatura que morreu no último minuto e ela volta à vida com 1 PV. Não funciona em quem morreu de velhice nem devolve partes do corpo perdidas.',
    classes: [],
  },
  {
    id: 'sending',
    namePt: 'Enviar Mensagem',
    nameEn: 'Sending',
    level: 3,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Ilimitado',
    rangeKind: 'special',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um fio de cobre fino' },
    componentsText: 'V, S, M (um fio de cobre fino)',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Você envia uma mensagem de até 25 palavras a uma criatura que conheça, em qualquer lugar do mesmo plano. Ela pode responder com até 25 palavras.',
    classes: [],
  },
  {
    id: 'sleet-storm',
    namePt: 'Tempestade de Granizo',
    nameEn: 'Sleet Storm',
    level: 3,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'cylinder', sizeMeters: 6, note: 'raio de 6 m, 6 m de altura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de pó e algumas gotas de água' },
    componentsText: 'V, S, M (uma pitada de pó e algumas gotas de água)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Granizo e chuva gelada preenchem um cilindro de 6 m de raio. A área é terreno difícil, fortemente obscurecida e obriga concentração (salvaguarda de Constituição) e Destreza para não escorregar.',
    save: 'dexterity',
    classes: [],
  },
  {
    id: 'slow',
    namePt: 'Lentidão',
    nameEn: 'Slow',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'cube', sizeMeters: 12 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gota de melaço' },
    componentsText: 'V, S, M (uma gota de melaço)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Até seis criaturas à sua escolha num cubo de 12 m fazem salvaguarda de Sabedoria ou ficam lentas: deslocamento reduzido, −2 de CA e Destreza, sem reações e apenas uma ação ou ação bônus por turno.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'speak-with-dead',
    namePt: 'Falar com os Mortos',
    nameEn: 'Speak with Dead',
    level: 3,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'incenso aceso' },
    componentsText: 'V, S, M (incenso aceso)',
    duration: '10 minutos',
    concentration: false,
    ritual: false,
    description:
      'Você concede a aparência de vida a um cadáver com boca e o faz responder a até cinco perguntas. Ele só sabe o que sabia em vida e é limitado pelo conhecimento que tinha.',
    classes: [],
  },
  {
    id: 'speak-with-plants',
    namePt: 'Falar com Plantas',
    nameEn: 'Speak with Plants',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '10 minutos',
    concentration: false,
    ritual: false,
    description:
      'Plantas a até 9 m ganham consciência e mobilidade limitada, podendo responder a perguntas e realizar tarefas simples (abrir caminho, entregar informação) por 10 min.',
    classes: [],
  },
  {
    id: 'spirit-guardians',
    namePt: 'Guardiões Espirituais',
    nameEn: 'Spirit Guardians',
    level: 3,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'sphere', sizeMeters: 4.5 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pergaminho com uma prece' },
    componentsText: 'V, S, M (um pergaminho com uma prece)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Espíritos protetores flutuam num raio de 4,5 m. Criaturas hostis na área têm o deslocamento reduzido à metade e, ao entrar ou começar o turno ali, fazem salvaguarda de Sabedoria ou sofrem 3d8 de dano radiante (ou necrótico, se você for mau; metade se passar).',
    save: 'wisdom',
    damage: [{ count: 3, sides: 8, bonus: 0, type: 'Radiante' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'stinking-cloud',
    namePt: 'Nuvem Fétida',
    nameEn: 'Stinking Cloud',
    level: 3,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um ovo podre ou folhas de repolho de gambá' },
    componentsText: 'V, S, M (um ovo podre ou folhas de repolho de gambá)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma nuvem amarela e nauseante de 6 m de raio surge. Cada criatura que comece o turno nela faz salvaguarda de Constituição ou gasta a ação vomitando; a área é fortemente obscurecida.',
    save: 'constitution',
    classes: [],
  },
  {
    id: 'tongues',
    namePt: 'Idiomas',
    nameEn: 'Tongues',
    level: 3,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: false, material: true },
    material: { text: 'um pequeno modelo de barro de um zigurate' },
    componentsText: 'V, M (um pequeno modelo de barro de um zigurate)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura que você toca entende qualquer idioma que ouça e, ao falar, é entendida por qualquer criatura que saiba ao menos um idioma.',
    classes: [],
  },
  {
    id: 'vampiric-touch',
    namePt: 'Toque Vampírico',
    nameEn: 'Vampiric Touch',
    level: 3,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Sua mão envolta em sombras drena vida. Faça um ataque de magia corpo a corpo: se acertar, o alvo sofre 3d6 de dano necrótico e você recupera metade do dano causado. Pode repetir o ataque com uma ação nos turnos seguintes.',
    attack: 'melee',
    damage: [{ count: 3, sides: 6, bonus: 0, type: 'Necrótico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'water-breathing',
    namePt: 'Respirar na Água',
    nameEn: 'Water Breathing',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um junco curto' },
    componentsText: 'V, S, M (um junco curto)',
    duration: '24 horas',
    concentration: false,
    ritual: true,
    description:
      'Até dez criaturas à sua escolha a até 9 m podem respirar debaixo d’água por 24 h, mantendo sua respiração normal.',
    classes: [],
  },
  {
    id: 'water-walk',
    namePt: 'Andar sobre a Água',
    nameEn: 'Water Walk',
    level: 3,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de cortiça' },
    componentsText: 'V, S, M (um pedaço de cortiça)',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    description:
      'Até dez criaturas à sua escolha a até 9 m podem se mover sobre qualquer superfície líquida como se fosse terreno sólido; se submergirem, voltam à superfície no fim do turno.',
    classes: [],
  },
  {
    id: 'wind-wall',
    namePt: 'Muralha de Vento',
    nameEn: 'Wind Wall',
    level: 3,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'line', sizeMeters: 15, note: '1,5 m de largura, 9 m de altura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um leque minúsculo e uma pena' },
    componentsText: 'V, S, M (um leque minúsculo e uma pena)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma parede de vento de 15 m de comprimento e 9 m de altura surge. Criaturas na área faz salvaguarda de Força ou sofrem 3d8 de dano de concussão; ela bloqueia flechas, gases e criaturas voadoras pequenas.',
    save: 'strength',
    damage: [{ count: 3, sides: 8, bonus: 0, type: 'Concussão' }],
    classes: [],
  },
];
