import type { Spell } from '../types.js';

/**
 * Magias de 7º nível do PHB 2014 (20). Ordem alfabética pelo nome em inglês.
 * `classes` fica VAZIO até o Prompt 6.2.
 */
export const LEVEL_7: readonly Spell[] = [
  {
    id: 'conjure-celestial',
    namePt: 'Convocar Celestial',
    nameEn: 'Conjure Celestial',
    level: 7,
    school: 'conjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você invoca um celestial de NC 4 ou menos que obedece às suas ordens. Se perder a concentração, a criatura pode ficar hostil.',
    upcast: { note: 'O NC máximo aumenta em 1 por nível de espaço acima do 7º.' },
    classes: [],
  },
  {
    id: 'delayed-blast-fireball',
    namePt: 'Bola de Fogo Retardada',
    nameEn: 'Delayed Blast Fireball',
    level: 7,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma bolinha de guano de morcego e enxofre' },
    componentsText: 'V, S, M (guano de morcego e enxofre)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma esfera de fogo retardado explode no ponto escolhido. Cada criatura na área faz salvaguarda de Destreza ou sofre 12d6 de dano de fogo (metade se passar). A cada turno você pode adiar a explosão e acumular +1d6 de dano.',
    save: 'dexterity',
    damage: [{ count: 12, sides: 6, bonus: 0, type: 'Fogo' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'divine-word',
    namePt: 'Palavra Divina',
    nameEn: 'Divine Word',
    level: 7,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você profere uma palavra divina. Cada criatura à sua escolha a até 9 m faz salvaguarda de Carisma: com 50 PV ou menos fica surda, 40 ou menos também cega, 30 ou menos também atordoada, 20 ou menos morre.',
    save: 'charisma',
    classes: [],
  },
  {
    id: 'etherealness',
    namePt: 'Etereidade',
    nameEn: 'Etherealness',
    level: 7,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Até 8 horas',
    concentration: false,
    ritual: false,
    description:
      'Você entra no Plano Etéreo, onde pode se mover em qualquer direção e ver o Plano Material. Ao retornar, você reaparece no mesmo lugar (ou no mais próximo desocupado).',
    upcast: { note: 'Com espaço de 8º ou superior, você pode levar até três criaturas voluntárias.' },
    classes: [],
  },
  {
    id: 'finger-of-death',
    namePt: 'Dedo da Morte',
    nameEn: 'Finger of Death',
    level: 7,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura a até 18 m faz salvaguarda de Constituição ou sofre 7d8 + 30 de dano necrótico (metade se passar). Um humanoide morto por esta magia vira um zumbi sob seu controle.',
    save: 'constitution',
    damage: [{ count: 7, sides: 8, bonus: 30, type: 'Necrótico' }],
    classes: [],
  },
  {
    id: 'fire-storm',
    namePt: 'Tempestade de Fogo',
    nameEn: 'Fire Storm',
    level: 7,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '45 m',
    rangeKind: 'ranged',
    rangeMeters: 45,
    area: { shape: 'cube', sizeMeters: 3, note: 'até dez cubos de 3 m contíguos' },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma tempestade de fogo atinge até dez cubos de 3 m de lado. Cada criatura na área faz salvaguarda de Destreza ou sofre 7d10 de dano de fogo (metade se passar); os cubos podem ser arranjados como você quiser.',
    save: 'dexterity',
    damage: [{ count: 7, sides: 10, bonus: 0, type: 'Fogo' }],
    classes: [],
  },
  {
    id: 'forcecage',
    namePt: 'Jaula de Força',
    nameEn: 'Forcecage',
    level: 7,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '30 m',
    rangeKind: 'ranged',
    rangeMeters: 30,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pó de rubi no valor de 1500 PO' },
    componentsText: 'V, S, M (pó de rubi no valor de 1500 PO)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma prisão de força mágica surge: uma caixa de 6 m de lado ou uma jaula de 6 m de raio. Criaturas dentro ficam presas; magias de teleporte exigem salvaguarda de Carisma para escapar.',
    save: 'charisma',
    classes: [],
  },
  {
    id: 'mirage-arcane',
    namePt: 'Miragem Arcana',
    nameEn: 'Mirage Arcane',
    level: 7,
    school: 'illusion',
    castingTime: '10 minutos',
    castingTimeKind: 'minute',
    range: 'Visão',
    rangeKind: 'sight',
    area: { shape: 'cube', sizeMeters: 1500 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '10 dias',
    concentration: false,
    ritual: false,
    description:
      'Você faz um terreno de até 1,5 km de lado parecer, soar, cheirar e até ser tocado como outro tipo de terreno, podendo incluir estruturas. A ilusão engana sentidos, mas não criaturas com Visão Verdadeira.',
    classes: [],
  },
  {
    id: 'mordenkainens-magnificent-mansion',
    namePt: 'Mansão Magnífica de Mordenkainen',
    nameEn: "Mordenkainen's Magnificent Mansion",
    level: 7,
    school: 'conjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '90 m',
    rangeKind: 'ranged',
    rangeMeters: 90,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um portal em miniatura, marfim, couro e seda, no valor de 15 PO' },
    componentsText: 'V, S, M (um portal em miniatura e marfim de 15 PO)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Você cria uma residência extradimensional com muitas salas, mobília e empregados espectrais. Até cem criaturas podem entrar por um portal invisível que dura 24 h.',
    classes: [],
  },
  {
    id: 'mordenkainens-sword',
    namePt: 'Espada de Mordenkainen',
    nameEn: "Mordenkainen's Sword",
    level: 7,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma espada de platina em miniatura no valor de 250 PO' },
    componentsText: 'V, S, M (uma espada de platina em miniatura de 250 PO)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma espada de força aparece. Com uma ação bônus, você a move até 6 m e faz um ataque de magia corpo a corpo contra uma criatura a até 1,5 m dela: 3d10 de dano de força.',
    attack: 'melee',
    damage: [{ count: 3, sides: 10, bonus: 0, type: 'Força' }],
    classes: [],
  },
  {
    id: 'plane-shift',
    namePt: 'Mudar de Plano',
    nameEn: 'Plane Shift',
    level: 7,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma haste de metal bifurcada no valor de 250 PO' },
    componentsText: 'V, S, M (uma haste de metal bifurcada de 250 PO)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você e até oito criaturas voluntárias se transportam para outro plano de existência. Criaturas involuntárias fazem salvaguarda de Carisma para resistir.',
    save: 'charisma',
    classes: [],
  },
  {
    id: 'prismatic-spray',
    namePt: 'Rajada Prismática',
    nameEn: 'Prismatic Spray',
    level: 7,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'cone', sizeMeters: 18 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Oito raios de luz multicolorida disparam num cone de 18 m. Cada criatura na área rola 1d8 para saber a cor: cada cor causa um efeito diferente (dano de vários tipos, cegueira, petrificação etc.).',
    save: 'dexterity',
    damage: [{ count: 10, sides: 6, bonus: 0, type: null }],
    classes: [],
  },
  {
    id: 'project-image',
    namePt: 'Projetar Imagem',
    nameEn: 'Project Image',
    level: 7,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '150 m',
    rangeKind: 'ranged',
    rangeMeters: 150,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pequena marionete no valor de 5 PO' },
    componentsText: 'V, S, M (uma pequena marionete de 5 PO)',
    duration: 'Concentração, até 1 dia',
    concentration: true,
    ritual: false,
    description:
      'Você cria uma cópia ilusória de si mesmo a até 150 m, que dura e pode se mover. Você vê através dos olhos dela e fala por ela, mas qualquer interação física revela a ilusão.',
    classes: [],
  },
  {
    id: 'regenerate',
    namePt: 'Regenerar',
    nameEn: 'Regenerate',
    level: 7,
    school: 'transmutation',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma roda de oração e água benta' },
    componentsText: 'V, S, M (uma roda de oração e água benta)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura que você toca recupera 4d8 + 15 pontos de vida e regenera 1 PV no início de cada turno. Membros perdidos são restaurados após 2 min.',
    classes: [],
  },
  {
    id: 'resurrection',
    namePt: 'Ressurreição',
    nameEn: 'Resurrection',
    level: 7,
    school: 'necromancy',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um diamante no valor de 1000 PO, consumido' },
    componentsText: 'V, S, M (um diamante no valor de 1000 PO, consumido)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você toca uma criatura morta há até um século que não tenha morrido de velhice e a traz de volta à vida com todos os PV. Ela sofre −4 em ataques e testes até dois descansos longos.',
    classes: [],
  },
  {
    id: 'reverse-gravity',
    namePt: 'Inverter Gravidade',
    nameEn: 'Reverse Gravity',
    level: 7,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '30 m',
    rangeKind: 'ranged',
    rangeMeters: 30,
    area: { shape: 'cylinder', sizeMeters: 15, note: 'raio de 15 m, 30 m de altura' },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pedra-ímã e limalha de ferro' },
    componentsText: 'V, S, M (uma pedra-ímã e limalha de ferro)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A gravidade se inverte num cilindro de 15 m de raio e 30 m de altura. Objetos e criaturas caem para cima; ao fim da magia, todos caem de volta (salvaguarda de Destreza para se agarrar).',
    save: 'dexterity',
    classes: [],
  },
  {
    id: 'sequester',
    namePt: 'Seqüestro',
    nameEn: 'Sequester',
    level: 7,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pó de diamante, esmeralda, rubi e safira no valor de 5000 PO, consumidos' },
    componentsText: 'V, S, M (pó de diamante, esmeralda, rubi e safira de 5000 PO, consumidos)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: false,
    description:
      'Você esconde um objeto ou uma criatura voluntária: ela fica invisível, não pode ser alvo de adivinhação nem detectada, e entra num estado de suspensão em que não envelhece.',
    classes: [],
  },
  {
    id: 'simulacrum',
    namePt: 'Simulacro',
    nameEn: 'Simulacrum',
    level: 7,
    school: 'illusion',
    castingTime: '12 horas',
    castingTimeKind: 'hour',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pó de rubi no valor de 1500 PO e uma réplica de neve ou gelo da criatura' },
    componentsText: 'V, S, M (pó de rubi de 1500 PO e uma réplica de neve/gelo)',
    duration: 'Até ser dissipada',
    concentration: false,
    ritual: false,
    description:
      'Você cria uma cópia de uma criatura ou humanoide dentro de 3 m. O simulacro é inimigo dela, tem metade dos PV e o mesmo equipamento; obedece a você.',
    classes: [],
  },
  {
    id: 'symbol',
    namePt: 'Símbolo',
    nameEn: 'Symbol',
    level: 7,
    school: 'abjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'mercúrio, fósforo e pó de diamante no valor de 1000 PO, consumidos' },
    componentsText: 'V, S, M (mercúrio, fósforo e pó de diamante de 1000 PO, consumidos)',
    duration: 'Até ser dissipada ou acionada',
    concentration: false,
    ritual: false,
    description:
      'Você inscreve um símbolo nocivo numa superfície. Quando acionado sob a condição que você definir, produz um efeito (morte, discórdia, medo, dor, sono, atordoamento ou insanidade) num raio de 18 m.',
    classes: [],
  },
  {
    id: 'teleport',
    namePt: 'Teleporte',
    nameEn: 'Teleport',
    level: 7,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você e até oito criaturas voluntárias se teleportam para um destino no mesmo plano. Um dado (1d100) determina a precisão do salto conforme o quanto você conhece o local.',
    classes: [],
  },
];
