import type { Spell } from '../types.js';

/**
 * Magias de 1º nível do PHB 2014 (62). Ordem alfabética pelo nome em inglês.
 * Alcances em metros (30 pés = 9 m, 60 pés = 18 m, 90 pés = 27 m, 120 pés = 36 m).
 * `classes` fica VAZIO até o Prompt 6.2.
 */
export const LEVEL_1: readonly Spell[] = [
  {
    id: 'alarm',
    namePt: 'Alarme',
    nameEn: 'Alarm',
    level: 1,
    school: 'abjuration',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    area: { shape: 'cube', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um sininho e um fio de prata' },
    componentsText: 'V, S, M (um sininho e um fio de prata)',
    duration: '8 horas',
    concentration: false,
    ritual: true,
    description:
      'Você protege uma área em cubo de 6 m. Escolha alerta (mental ou sonoro) e quais criaturas não disparam o alarme. Quando uma criatura do tamanho Pequeno ou maior entrar na área, o alarme dispara.',
    classes: [],
  },
  {
    id: 'animal-friendship',
    namePt: 'Amizade Animal',
    nameEn: 'Animal Friendship',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de comida' },
    componentsText: 'V, S, M (um pedaço de comida)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    description:
      'Uma besta de INT 3 ou menos a até 9 m faz uma salvaguarda de Sabedoria. Se falhar, fica enfeitiçada por você por 24 h. A magia acaba se você ou um aliado ferir o alvo.',
    save: 'wisdom',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'armor-of-agathys',
    namePt: 'Armadura de Agathys',
    nameEn: 'Armor of Agathys',
    level: 1,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um copo de água' },
    componentsText: 'V, S, M (um copo de água)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma proteção de gelo o cobre: você ganha 5 PV temporários. Enquanto os tiver, uma criatura que o acertar com um ataque corpo a corpo sofre 5 de dano de frio.',
    damage: [{ count: 0, sides: 0, bonus: 5, type: 'Frio' }],
    upcast: { note: 'PV temporários e dano de frio aumentam em 5 por nível de espaço acima do 1º.' },
    classes: [],
  },
  {
    id: 'arms-of-hadar',
    namePt: 'Braços de Hadar',
    nameEn: 'Arms of Hadar',
    level: 1,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'sphere', sizeMeters: 3, note: 'origem em você' },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Tentáculos de energia sombria brotam de você. Cada criatura a até 3 m de você faz uma salvaguarda de Força; se falhar, sofre 2d6 de dano necrótico e não pode fazer reações no próximo turno.',
    save: 'strength',
    damage: [{ count: 2, sides: 6, bonus: 0, type: 'Necrótico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'bane',
    namePt: 'Perdição',
    nameEn: 'Bane',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gota de sangue' },
    componentsText: 'V, S, M (uma gota de sangue)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Até três criaturas a até 9 m fazem salvaguarda de Carisma. Quem falhar subtrai 1d4 das jogadas de ataque e testes de resistência enquanto a magia durar.',
    save: 'charisma',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'bless',
    namePt: 'Bênção',
    nameEn: 'Bless',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um borrifo de água benta' },
    componentsText: 'V, S, M (um borrifo de água benta)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Até três criaturas à sua escolha a até 9 m somam 1d4 às jogadas de ataque e aos testes de resistência enquanto a magia durar.',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'burning-hands',
    namePt: 'Mãos Flamejantes',
    nameEn: 'Burning Hands',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'cone', sizeMeters: 4.5 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Um cone de chamas de 4,5 m sai das suas mãos. Cada criatura na área faz salvaguarda de Destreza; se falhar, sofre 3d6 de dano de fogo, ou metade se passar. Objetos inflamáveis acendem.',
    save: 'dexterity',
    damage: [{ count: 3, sides: 6, bonus: 0, type: 'Fogo' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'charm-person',
    namePt: 'Enfeitiçar Pessoa',
    nameEn: 'Charm Person',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Um humanoide a até 9 m faz salvaguarda de Sabedoria (com vantagem se você estiver lutando com ele). Se falhar, fica enfeitiçado por você e o trata como conhecido amigável. A magia acaba se você ou seus aliados o ferirem.',
    save: 'wisdom',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'chromatic-orb',
    namePt: 'Orbe Cromático',
    nameEn: 'Chromatic Orb',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um diamante de 50 PO' },
    componentsText: 'V, S, M (um diamante de 50 PO)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você arremessa uma esfera de energia. Faça um ataque de magia à distância contra uma criatura a até 27 m: se acertar, ela sofre 3d8 de um tipo de dano à sua escolha (ácido, frio, fogo, elétrico, veneno ou trovão).',
    attack: 'ranged',
    damage: [{ count: 3, sides: 8, bonus: 0, type: null }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'color-spray',
    namePt: 'Leque de Cores',
    nameEn: 'Color Spray',
    level: 1,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'cone', sizeMeters: 4.5 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de pó ou areia colorida' },
    componentsText: 'V, S, M (uma pitada de pó ou areia colorida)',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Um cone de luzes cintilantes de 4,5 m. Role 6d10: o total é o montante de PV de criaturas que podem ser cegadas, do menor PV ao maior. Cada criatura afetada fica cega até o fim do seu próximo turno.',
    upcast: { note: 'Some 2d10 ao montante de PV por nível de espaço acima do 1º.' },
    classes: [],
  },
  {
    id: 'command',
    namePt: 'Comando',
    nameEn: 'Command',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Você profere uma palavra de comando a uma criatura a até 18 m que possa ouvi-lo. Se ela falhar numa salvaguarda de Sabedoria, obedece no próximo turno (aproximar, largar, fugir, deitar, parar).',
    save: 'wisdom',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'compelled-duel',
    namePt: 'Duelo Compelido',
    nameEn: 'Compelled Duel',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura a até 9 m faz salvaguarda de Sabedoria. Se falhar, tem desvantagem em ataques contra outras criaturas e deve fazer um teste para se afastar de você; a magia acaba se você atacar outra criatura ou se afastar demais.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'comprehend-languages',
    namePt: 'Compreender Idiomas',
    nameEn: 'Comprehend Languages',
    level: 1,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de fuligem e sal' },
    componentsText: 'V, S, M (uma pitada de fuligem e sal)',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    description:
      'Por 1 hora você entende o sentido literal de qualquer idioma falado que ouvir e de qualquer texto escrito que tocar (não decifra códigos nem símbolos secretos).',
    classes: [],
  },
  {
    id: 'create-or-destroy-water',
    namePt: 'Criar ou Destruir Água',
    nameEn: 'Create or Destroy Water',
    level: 1,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gota de água (criar) ou alguns grãos de areia (destruir)' },
    componentsText: 'V, S, M (uma gota de água ou alguns grãos de areia)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você cria até 40 litros de água limpa (ou chuva numa área de 9 m de lado) ou destrói até 40 litros de água (ou neblina num cubo de 9 m).',
    upcast: { note: 'Cria ou destrói 40 litros adicionais por nível de espaço acima do 1º.' },
    classes: [],
  },
  {
    id: 'cure-wounds',
    namePt: 'Curar Ferimentos',
    nameEn: 'Cure Wounds',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura que você toca recupera 1d8 + o seu modificador de atributo de conjuração em pontos de vida. Não afeta mortos-vivos nem constructos.',
    healing: { count: 1, sides: 8, bonus: 0, type: null },
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'detect-evil-and-good',
    namePt: 'Detectar o Bem e o Mal',
    nameEn: 'Detect Evil and Good',
    level: 1,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Por 10 minutos você sabe se há aberrações, celestiais, corruptores, elementais, fadas, imundícies ou mortos-vivos a até 9 m, e sente se um lugar ou objeto foi consagrado ou profanado.',
    classes: [],
  },
  {
    id: 'detect-magic',
    namePt: 'Detectar Magia',
    nameEn: 'Detect Magic',
    level: 1,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: true,
    description:
      'Por 10 minutos você sente magia a até 9 m e, com uma ação, pode ver um halo em torno de criaturas/objetos mágicos visíveis e descobrir a escola da magia.',
    classes: [],
  },
  {
    id: 'detect-poison-and-disease',
    namePt: 'Detectar Veneno e Doença',
    nameEn: 'Detect Poison and Disease',
    level: 1,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'emanation', sizeMeters: 9 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma folha de teixo' },
    componentsText: 'V, S, M (uma folha de teixo)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: true,
    description:
      'Por 10 minutos você sente venenos, criaturas venenosas e doenças mágicas a até 9 m, e identifica o tipo em cada caso.',
    classes: [],
  },
  {
    id: 'disguise-self',
    namePt: 'Disfarce',
    nameEn: 'Disguise Self',
    level: 1,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Você faz sua aparência (incluindo roupas e equipamento) parecer diferente até 1 h, podendo parecer 30 cm mais alto ou baixo. Um teste de Investigação contra a CD da magia revela o disfarce.',
    classes: [],
  },
  {
    id: 'dissonant-whispers',
    namePt: 'Sussurros Dissonantes',
    nameEn: 'Dissonant Whispers',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você sussurra uma melodia dissonante a uma criatura a até 18 m. Se ela falhar numa salvaguarda de Sabedoria, sofre 3d6 de dano psíquico e deve usar a reação para se afastar de você pelo caminho mais seguro.',
    save: 'wisdom',
    damage: [{ count: 3, sides: 6, bonus: 0, type: 'Psíquico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'divine-favor',
    namePt: 'Favor Divino',
    nameEn: 'Divine Favor',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Sua oração imbui suas armas. Enquanto durar, seus ataques com arma causam 1d4 de dano radiante adicional ao acertar.',
    classes: [],
  },
  {
    id: 'ensnaring-strike',
    namePt: 'Golpe Enredante',
    nameEn: 'Ensnaring Strike',
    level: 1,
    school: 'conjuration',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar uma criatura com uma arma, vinhas a prendem. O alvo (Grande ou menor) faz salvaguarda de Força ou fica impedido, sofrendo 1d6 de dano perfurante no início de cada turno.',
    save: 'strength',
    damage: [{ count: 1, sides: 6, bonus: 0, type: 'Perfurante' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'entangle',
    namePt: 'Enredar',
    nameEn: 'Entangle',
    level: 1,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    area: { shape: 'cube', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Ervas e cipós agarram o solo numa área de 6 m de lado. Cada criatura na área faz salvaguarda de Força ou fica impedida; quem falhar pode repetir a salvaguarda no fim de cada turno.',
    save: 'strength',
    classes: [],
  },
  {
    id: 'expeditious-retreat',
    namePt: 'Retirada Acelerada',
    nameEn: 'Expeditious Retreat',
    level: 1,
    school: 'transmutation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Enquanto durar, você pode usar uma ação bônus em cada um dos seus turnos para executar a ação Correr.',
    classes: [],
  },
  {
    id: 'faerie-fire',
    namePt: 'Fogo-Fátuo',
    nameEn: 'Faerie Fire',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'cube', sizeMeters: 6 },
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Objetos e criaturas numa área de 6 m de lado ficam delineados por luz. Cada criatura faz salvaguarda de Destreza ou, enquanto a magia durar, emite luz fraca, não pode se beneficiar de invisibilidade e ataques contra ela têm vantagem.',
    save: 'dexterity',
    classes: [],
  },
  {
    id: 'false-life',
    namePt: 'Vida Falsa',
    nameEn: 'False Life',
    level: 1,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gota de sangue' },
    componentsText: 'V, S, M (uma gota de sangue)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description:
      'Uma reserva necromântica de vitalidade lhe concede 1d4 + 4 pontos de vida temporários por 1 hora.',
    healing: { count: 1, sides: 4, bonus: 4, type: null },
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'feather-fall',
    namePt: 'Queda Suave',
    nameEn: 'Feather Fall',
    level: 1,
    school: 'transmutation',
    castingTime: '1 reação*',
    castingTimeKind: 'reaction',
    reactionTrigger:
      'quando você ou uma criatura a até 18 m cai — a reação é usada ao começar a queda',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: true },
    material: { text: 'uma pena ou penugem' },
    componentsText: 'V, M (uma pena ou penugem)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Escolha até cinco criaturas que estão caindo. A velocidade de queda delas cai para 18 m por rodada até a magia acabar; se aterrissarem antes, não sofrem dano de queda e podem pousar de pé.',
    classes: [],
  },
  {
    id: 'find-familiar',
    namePt: 'Encontrar Familiar',
    nameEn: 'Find Familiar',
    level: 1,
    school: 'conjuration',
    castingTime: '1 hora',
    castingTimeKind: 'hour',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'carvão, incenso e ervas no valor de 10 PO, consumidos no braseiro' },
    componentsText: 'V, S, M (carvão, incenso e ervas no valor de 10 PO, consumidos)',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    description:
      'Você obtém a lealdade de um espírito que assume a forma de um animal escolhido (corvo, gato, caranguejo, sapo, falcão, lagarto, polvo, coruja, rato, aranha, doninha etc.). O familiar age de modo independente e pode canalizar suas magias de toque.',
    classes: [],
  },
  {
    id: 'fog-cloud',
    namePt: 'Nuvem de Neblina',
    nameEn: 'Fog Cloud',
    level: 1,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    area: { shape: 'sphere', sizeMeters: 6 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Uma esfera de névoa densa de 6 m de raio surge num ponto a até 36 m, tornando a área fortemente obscurecida. Um vento moderado a dispersa.',
    upcast: { note: 'O raio aumenta 6 m por nível de espaço acima do 1º.' },
    classes: [],
  },
  {
    id: 'goodberry',
    namePt: 'Baga Abençoada',
    nameEn: 'Goodberry',
    level: 1,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um raminho de visco' },
    componentsText: 'V, S, M (um raminho de visco)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Até dez bagas surgem na sua mão, imbuídas de magia. Comer uma consome a ação e cura 1 PV, além de nutrir o suficiente para um dia. As bagas perdem o efeito após 24 h.',
    healing: { count: 0, sides: 0, bonus: 1, type: null },
    classes: [],
  },
  {
    id: 'grease',
    namePt: 'Graxa',
    nameEn: 'Grease',
    level: 1,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'cube', sizeMeters: 3 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pouco de manteiga' },
    componentsText: 'V, S, M (um pouco de manteiga)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Uma graxa escorregadia cobre o solo numa área de 3 m de lado. Cada criatura na área faz salvaguarda de Destreza ou cai prostrada; quem entrar ou terminar o turno ali repete a salvaguarda.',
    save: 'dexterity',
    classes: [],
  },
  {
    id: 'guiding-bolt',
    namePt: 'Raio Guiador',
    nameEn: 'Guiding Bolt',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Um clarão atinge uma criatura a até 36 m. Faça um ataque de magia à distância: se acertar, o alvo sofre 4d6 de dano radiante e o próximo ataque contra ele antes do fim do seu próximo turno tem vantagem.',
    attack: 'ranged',
    damage: [{ count: 4, sides: 6, bonus: 0, type: 'Radiante' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'hail-of-thorns',
    namePt: 'Saraivada de Espinhos',
    nameEn: 'Hail of Thorns',
    level: 1,
    school: 'conjuration',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar com um ataque à distância, a munição explode em espinhos: o alvo e cada criatura a até 1,5 m dele fazem salvaguarda de Destreza, sofrendo 1d10 de dano perfurante se falharem (metade se passarem).',
    save: 'dexterity',
    damage: [{ count: 1, sides: 10, bonus: 0, type: 'Perfurante' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'healing-word',
    namePt: 'Palavra Curativa',
    nameEn: 'Healing Word',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura visível a até 18 m recupera 1d4 + o seu modificador de atributo de conjuração em pontos de vida. Não afeta mortos-vivos nem constructos.',
    healing: { count: 1, sides: 4, bonus: 0, type: null },
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'hellish-rebuke',
    namePt: 'Repreensão Infernal',
    nameEn: 'Hellish Rebuke',
    level: 1,
    school: 'evocation',
    castingTime: '1 reação*',
    castingTimeKind: 'reaction',
    reactionTrigger: 'quando uma criatura a até 18 m que você possa ver o fere',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'A criatura que o feriu é envolta em fogo infernal. Ela faz salvaguarda de Destreza; se falhar, sofre 2d10 de dano de fogo, ou metade se passar.',
    save: 'dexterity',
    damage: [{ count: 2, sides: 10, bonus: 0, type: 'Fogo' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'heroism',
    namePt: 'Heroísmo',
    nameEn: 'Heroism',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura voluntária que você toca fica imune ao medo e ganha pontos de vida temporários iguais ao seu modificador de atributo de conjuração no início de cada turno dela.',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'hex',
    namePt: 'Azar',
    nameEn: 'Hex',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'o olho petrificado de um tritão' },
    componentsText: 'V, S, M (o olho petrificado de um tritão)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você amaldiçoa uma criatura a até 27 m. Enquanto durar, você causa 1d6 de dano necrótico adicional a ela sempre que a acertar, e ela tem desvantagem em testes de atributo de uma habilidade escolhida.',
    damage: [{ count: 1, sides: 6, bonus: 0, type: 'Necrótico' }],
    upcast: { note: 'Com espaço de 3º ou 4º nível dura até 8 h; de 5º ou superior, até 24 h.' },
    classes: [],
  },
  {
    id: 'hunters-mark',
    namePt: 'Marca do Caçador',
    nameEn: "Hunter's Mark",
    level: 1,
    school: 'divination',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    description:
      'Você marca uma criatura a até 27 m. Enquanto durar, seus ataques com arma contra ela causam 1d6 de dano adicional do mesmo tipo da arma, e você tem vantagem em Sobrevivência/Percepção para encontrá-la.',
    upcast: { note: 'Dura até 8 h com espaço de 3º/4º nível e até 24 h com espaço de 5º ou superior.' },
    classes: [],
  },
  {
    id: 'identify',
    namePt: 'Identificar',
    nameEn: 'Identify',
    level: 1,
    school: 'divination',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pérola de 100 PO e uma pena de coruja' },
    componentsText: 'V, S, M (uma pérola de 100 PO e uma pena de coruja)',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    description:
      'Você toca um objeto e descobre suas propriedades mágicas, como usá-lo, se exige sintonia e quais magias o afetam. Se tocar uma criatura, descobre as magias ativas sobre ela.',
    classes: [],
  },
  {
    id: 'illusory-script',
    namePt: 'Escrita Ilusória',
    nameEn: 'Illusory Script',
    level: 1,
    school: 'illusion',
    castingTime: '1 minuto',
    castingTimeKind: 'minute',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: false, somatic: true, material: true },
    material: { text: 'uma tinta de chumbo no valor de 10 PO, consumida' },
    componentsText: 'S, M (uma tinta de chumbo no valor de 10 PO, consumida)',
    duration: '10 dias',
    concentration: false,
    ritual: true,
    description:
      'Você escreve num pergaminho, papel ou outro material e o imbui de ilusão: criaturas escolhidas leem a mensagem verdadeira, outras veem texto diferente ou ilegível. Uma criatura com Visão Verdadeira vê o texto real.',
    classes: [],
  },
  {
    id: 'inflict-wounds',
    namePt: 'Infligir Ferimentos',
    nameEn: 'Inflict Wounds',
    level: 1,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Faça um ataque de magia corpo a corpo contra uma criatura que você possa alcançar. Se acertar, o alvo sofre 3d10 de dano necrótico.',
    attack: 'melee',
    damage: [{ count: 3, sides: 10, bonus: 0, type: 'Necrótico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'jump',
    namePt: 'Salto',
    nameEn: 'Jump',
    level: 1,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'a pata traseira de um gafanhoto' },
    componentsText: 'V, S, M (a pata traseira de um gafanhoto)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura que você toca tem a distância de salto triplicada até o fim da magia. Cada salto continua custando movimento.',
    classes: [],
  },
  {
    id: 'longstrider',
    namePt: 'Passo Largo',
    nameEn: 'Longstrider',
    level: 1,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de terra' },
    componentsText: 'V, S, M (uma pitada de terra)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    description: 'Uma criatura que você toca tem o deslocamento aumentado em 3 m até o fim da magia.',
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'mage-armor',
    namePt: 'Armadura Arcana',
    nameEn: 'Mage Armor',
    level: 1,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de couro curtido' },
    componentsText: 'V, S, M (um pedaço de couro curtido)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura voluntária que não esteja usando armadura tem a CA base calculada como 13 + o modificador de Destreza até o fim da magia.',
    classes: [],
  },
  {
    id: 'magic-missile',
    namePt: 'Mísseis Mágicos',
    nameEn: 'Magic Missile',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '36 m',
    rangeKind: 'ranged',
    rangeMeters: 36,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Você cria três dardos de energia. Cada um atinge uma criatura à sua escolha que você possa ver a até 36 m e causa 1d4 + 1 de dano de força. Todos os dardos acertam ao mesmo tempo.',
    damage: [{ count: 3, sides: 4, bonus: 3, type: 'Força' }],
    upcast: { extraTargetsPerSlot: 1 },
    classes: [],
  },
  {
    id: 'protection-from-evil-and-good',
    namePt: 'Proteção contra o Bem e o Mal',
    nameEn: 'Protection from Evil and Good',
    level: 1,
    school: 'abjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Toque',
    rangeKind: 'touch',
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'água benta ou prata e ferro em pó, consumidos' },
    componentsText: 'V, S, M (água benta ou prata e ferro em pó, consumidos)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura voluntária que você toca fica protegida contra aberrações, celestiais, corruptores, elementais, fadas, imundícies e mortos-vivos: eles têm desvantagem nos ataques contra ela e ela não pode ser enfeitiçada, amedrontada nem possuída por eles.',
    classes: [],
  },
  {
    id: 'purify-food-and-drink',
    namePt: 'Purificar Alimentos e Bebidas',
    nameEn: 'Purify Food and Drink',
    level: 1,
    school: 'transmutation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '3 m',
    rangeKind: 'ranged',
    rangeMeters: 3,
    area: { shape: 'sphere', sizeMeters: 1.5 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    description:
      'Alimentos e bebidas não mágicos numa esfera de 1,5 m de raio ficam livres de veneno e doença.',
    classes: [],
  },
  {
    id: 'ray-of-sickness',
    namePt: 'Raio de Enjoo',
    nameEn: 'Ray of Sickness',
    level: 1,
    school: 'necromancy',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Faça um ataque de magia à distância contra uma criatura a até 18 m: se acertar, ela sofre 2d8 de dano de veneno e faz salvaguarda de Constituição; se falhar, fica envenenada até o fim do seu próximo turno.',
    attack: 'ranged',
    save: 'constitution',
    damage: [{ count: 2, sides: 8, bonus: 0, type: 'Veneno' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'sanctuary',
    namePt: 'Santuário',
    nameEn: 'Sanctuary',
    level: 1,
    school: 'abjuration',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pequeno espelho de prata' },
    componentsText: 'V, S, M (um pequeno espelho de prata)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Uma criatura a até 9 m fica protegida: quem tentar atacá-la ou lançar magia prejudicial sobre ela deve fazer salvaguarda de Sabedoria ou escolher outro alvo. A proteção acaba se a criatura atacar ou lançar magia.',
    classes: [],
  },
  {
    id: 'searing-smite',
    namePt: 'Golpe Flamejante',
    nameEn: 'Searing Smite',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar com uma arma corpo a corpo, ela arde com chamas: o alvo sofre 1d6 de dano de fogo adicional e faz salvaguarda de Constituição ou pega fogo, sofrendo 1d6 de dano de fogo no início de cada turno até apagar.',
    save: 'constitution',
    damage: [{ count: 1, sides: 6, bonus: 0, type: 'Fogo' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'shield',
    namePt: 'Escudo',
    nameEn: 'Shield',
    level: 1,
    school: 'abjuration',
    castingTime: '1 reação*',
    castingTimeKind: 'reaction',
    reactionTrigger:
      'quando você é atingido por um ataque ou alvo da magia Mísseis Mágicos',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    description:
      'Uma barreira invisível aparece: até o início do seu próximo turno você ganha +5 de CA, inclusive contra o ataque que disparou a reação, e não sofre dano de Mísseis Mágicos.',
    classes: [],
  },
  {
    id: 'shield-of-faith',
    namePt: 'Escudo da Fé',
    nameEn: 'Shield of Faith',
    level: 1,
    school: 'abjuration',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pergaminho com um texto sagrado' },
    componentsText: 'V, S, M (um pergaminho com um texto sagrado)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Um campo cintilante cerca uma criatura à sua escolha a até 18 m, dando a ela +2 de CA enquanto a magia durar.',
    classes: [],
  },
  {
    id: 'silent-image',
    namePt: 'Imagem Silenciosa',
    nameEn: 'Silent Image',
    level: 1,
    school: 'illusion',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    area: { shape: 'cube', sizeMeters: 4.5 },
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de lã' },
    componentsText: 'V, S, M (um pedaço de lã)',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    description:
      'Você cria a imagem visual de um objeto, criatura ou fenômeno dentro de um cubo de 4,5 m. Com uma ação, você pode mover a imagem; interagir fisicamente com ela revela que é falsa.',
    classes: [],
  },
  {
    id: 'sleep',
    namePt: 'Sono',
    nameEn: 'Sleep',
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '27 m',
    rangeKind: 'ranged',
    rangeMeters: 27,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma pitada de areia, pétalas de rosa ou um grilo' },
    componentsText: 'V, S, M (uma pitada de areia, pétalas de rosa ou um grilo)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    description:
      'Role 5d8: esse montante de PV de criaturas a até 27 m é afetado, do menor PV atual ao maior. Cada criatura afetada cai inconsciente por 1 minuto (acorda se sofrer dano ou se alguém usar uma ação para sacudi-la).',
    upcast: { note: 'Some 2d8 ao montante de PV por nível de espaço acima do 1º.' },
    classes: [],
  },
  {
    id: 'speak-with-animals',
    namePt: 'Falar com Animais',
    nameEn: 'Speak with Animals',
    level: 1,
    school: 'divination',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: '10 minutos',
    concentration: false,
    ritual: true,
    description:
      'Por 10 minutos você compreende e pode falar verbalmente com bestas. O conhecimento das bestas é limitado ao que elas percebem.',
    classes: [],
  },
  {
    id: 'tashas-hideous-laughter',
    namePt: 'Risada Medonha de Tasha',
    nameEn: "Tasha's Hideous Laughter",
    level: 1,
    school: 'enchantment',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'pequenas tortas e uma pena que se agita no ar' },
    componentsText: 'V, S, M (pequenas tortas e uma pena)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Uma criatura de INT 4 ou mais a até 9 m faz salvaguarda de Sabedoria ou cai prostrada, incapaz de se levantar e de agir, rindo incontrolavelmente. Repete a salvaguarda a cada turno e com vantagem se sofrer dano.',
    save: 'wisdom',
    classes: [],
  },
  {
    id: 'tensers-floating-disk',
    namePt: 'Disco Flutuante de Tenser',
    nameEn: "Tenser's Floating Disk",
    level: 1,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'uma gota de mercúrio' },
    componentsText: 'V, S, M (uma gota de mercúrio)',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    description:
      'Um disco circular de força de 90 cm de diâmetro flutua 1 m acima do chão, carregando até 250 kg. Ele o segue a até 6 m e se mantém a 1 m de altura.',
    classes: [],
  },
  {
    id: 'thunderous-smite',
    namePt: 'Golpe Trovejante',
    nameEn: 'Thunderous Smite',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar com uma arma corpo a corpo, um trovão retumba: o alvo sofre 2d6 de dano de trovão adicional e, se falhar numa salvaguarda de Força, é empurrado 3 m e cai prostrado.',
    save: 'strength',
    damage: [{ count: 2, sides: 6, bonus: 0, type: 'Trovão' }],
    classes: [],
  },
  {
    id: 'thunderwave',
    namePt: 'Onda Trovejante',
    nameEn: 'Thunderwave',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: 'Pessoal',
    rangeKind: 'self',
    area: { shape: 'cube', sizeMeters: 4.5 },
    components: { verbal: true, somatic: true, material: false },
    componentsText: 'V, S',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    description:
      'Uma onda de força trovejante varre um cubo de 4,5 m a partir de você. Cada criatura na área faz salvaguarda de Constituição: se falhar, sofre 2d8 de dano de trovão e é empurrada 3 m; se passar, sofre metade e não é empurrada.',
    save: 'constitution',
    damage: [{ count: 2, sides: 8, bonus: 0, type: 'Trovão' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'unseen-servant',
    namePt: 'Servo Invisível',
    nameEn: 'Unseen Servant',
    level: 1,
    school: 'conjuration',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '18 m',
    rangeKind: 'ranged',
    rangeMeters: 18,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um pedaço de barbante e madeira' },
    componentsText: 'V, S, M (um pedaço de barbante e madeira)',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    description:
      'Uma força invisível e sem mente realiza tarefas simples que você ordena (buscar coisas, limpar, servir à mesa) dentro de até 18 m. Ele tem CA 10, 1 PV e FOR 2.',
    classes: [],
  },
  {
    id: 'witch-bolt',
    namePt: 'Raio Bruxo',
    nameEn: 'Witch Bolt',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação',
    castingTimeKind: 'action',
    range: '9 m',
    rangeKind: 'ranged',
    rangeMeters: 9,
    components: { verbal: true, somatic: true, material: true },
    material: { text: 'um graveto de uma árvore atingida por um raio' },
    componentsText: 'V, S, M (um graveto de uma árvore atingida por um raio)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'Um feixe de energia crepitante atinge uma criatura a até 9 m. Faça um ataque de magia à distância: se acertar, causa 1d12 de dano elétrico e, nos turnos seguintes, você pode usar a ação para causar 1d12 automaticamente, desde que mantenha a concentração e o alvo esteja no alcance.',
    attack: 'ranged',
    damage: [{ count: 1, sides: 12, bonus: 0, type: 'Elétrico' }],
    upcast: { extraDicePerSlot: 1 },
    classes: [],
  },
  {
    id: 'wrathful-smite',
    namePt: 'Golpe Irado',
    nameEn: 'Wrathful Smite',
    level: 1,
    school: 'evocation',
    castingTime: '1 ação bônus',
    castingTimeKind: 'bonusAction',
    range: 'Pessoal',
    rangeKind: 'self',
    components: { verbal: true, somatic: false, material: false },
    componentsText: 'V',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    description:
      'A próxima vez que você acertar com uma arma corpo a corpo, o alvo sofre 1d6 de dano psíquico adicional e faz salvaguarda de Sabedoria ou fica amedrontado por você até o fim da magia.',
    save: 'wisdom',
    damage: [{ count: 1, sides: 6, bonus: 0, type: 'Psíquico' }],
    classes: [],
  },
];
