import type { CanonicalWeapon } from './types.js';

/**
 * Lista fechada das 37 armas do PHB 2014.
 *
 * 10 simples corpo a corpo + 4 simples à distância + 18 marciais corpo a corpo +
 * 5 marciais à distância. O `id` é o valor gravado em
 * `item.details.canonicalWeaponId` e comparado pela proficiência de arma — NÃO
 * renomeie um id já publicado.
 *
 * Os nomes em português seguem a tradução usual da mesa; `nameEn` é só
 * referência. O dano é o do livro (a zarabatana tem dano plano 1, representado
 * por `damageBonus`). Os alcances estão em METROS (1 pé = 0,3 m) — alguns são
 * fracionários (zarabatana 7,5 m, rede 1,5 m) e o editor os arredonda ao
 * gravar, porque os campos de alcance da arma são inteiros.
 */
export const WEAPONS: readonly CanonicalWeapon[] = [
  // --- Armas simples de corpo a corpo (10) ----------------------------------
  {
    id: 'club',
    namePt: 'Clava',
    nameEn: 'Club',
    category: 'simple',
    type: 'melee',
    properties: ['light'],
    damageDie: { count: 1, sides: 4 },
    damageType: 'Concussão',
  },
  {
    id: 'dagger',
    namePt: 'Adaga',
    nameEn: 'Dagger',
    category: 'simple',
    type: 'melee',
    properties: ['finesse', 'light', 'thrown'],
    damageDie: { count: 1, sides: 4 },
    damageType: 'Perfurante',
    rangeNormal: 6,
    rangeLong: 18,
  },
  {
    id: 'greatclub',
    namePt: 'Clava grande',
    nameEn: 'Greatclub',
    category: 'simple',
    type: 'melee',
    properties: ['two-handed'],
    damageDie: { count: 1, sides: 8 },
    damageType: 'Concussão',
  },
  {
    id: 'handaxe',
    namePt: 'Machadinha',
    nameEn: 'Handaxe',
    category: 'simple',
    type: 'melee',
    properties: ['light', 'thrown'],
    damageDie: { count: 1, sides: 6 },
    damageType: 'Cortante',
    rangeNormal: 6,
    rangeLong: 18,
  },
  {
    id: 'javelin',
    namePt: 'Azagaia',
    nameEn: 'Javelin',
    category: 'simple',
    type: 'melee',
    properties: ['thrown'],
    damageDie: { count: 1, sides: 6 },
    damageType: 'Perfurante',
    rangeNormal: 9,
    rangeLong: 36,
  },
  {
    id: 'light-hammer',
    namePt: 'Martelo leve',
    nameEn: 'Light hammer',
    category: 'simple',
    type: 'melee',
    properties: ['light', 'thrown'],
    damageDie: { count: 1, sides: 4 },
    damageType: 'Concussão',
    rangeNormal: 6,
    rangeLong: 18,
  },
  {
    id: 'mace',
    namePt: 'Maça',
    nameEn: 'Mace',
    category: 'simple',
    type: 'melee',
    properties: [],
    damageDie: { count: 1, sides: 6 },
    damageType: 'Concussão',
  },
  {
    id: 'quarterstaff',
    namePt: 'Bordão',
    nameEn: 'Quarterstaff',
    category: 'simple',
    type: 'melee',
    properties: ['versatile'],
    versatileDie: 8,
    damageDie: { count: 1, sides: 6 },
    damageType: 'Concussão',
  },
  {
    id: 'sickle',
    namePt: 'Foice',
    nameEn: 'Sickle',
    category: 'simple',
    type: 'melee',
    properties: ['light'],
    damageDie: { count: 1, sides: 4 },
    damageType: 'Cortante',
  },
  {
    id: 'spear',
    namePt: 'Lança',
    nameEn: 'Spear',
    category: 'simple',
    type: 'melee',
    properties: ['thrown', 'versatile'],
    versatileDie: 8,
    damageDie: { count: 1, sides: 6 },
    damageType: 'Perfurante',
    rangeNormal: 6,
    rangeLong: 18,
  },

  // --- Armas simples à distância (4) ----------------------------------------
  {
    id: 'light-crossbow',
    namePt: 'Besta leve',
    nameEn: 'Light crossbow',
    category: 'simple',
    type: 'ranged',
    properties: ['ammunition', 'loading', 'two-handed'],
    damageDie: { count: 1, sides: 8 },
    damageType: 'Perfurante',
    rangeNormal: 24,
    rangeLong: 96,
    ammoType: 'Virote',
  },
  {
    id: 'dart',
    namePt: 'Dardo',
    nameEn: 'Dart',
    category: 'simple',
    type: 'ranged',
    properties: ['finesse', 'thrown'],
    damageDie: { count: 1, sides: 4 },
    damageType: 'Perfurante',
    rangeNormal: 6,
    rangeLong: 18,
  },
  {
    id: 'shortbow',
    namePt: 'Arco curto',
    nameEn: 'Shortbow',
    category: 'simple',
    type: 'ranged',
    properties: ['ammunition', 'two-handed'],
    damageDie: { count: 1, sides: 6 },
    damageType: 'Perfurante',
    rangeNormal: 24,
    rangeLong: 96,
    ammoType: 'Flecha',
  },
  {
    id: 'sling',
    namePt: 'Funda',
    nameEn: 'Sling',
    category: 'simple',
    type: 'ranged',
    properties: ['ammunition'],
    damageDie: { count: 1, sides: 4 },
    damageType: 'Concussão',
    rangeNormal: 9,
    rangeLong: 36,
    ammoType: 'Bala de funda',
  },

  // --- Armas marciais de corpo a corpo (18) ---------------------------------
  {
    id: 'battleaxe',
    namePt: 'Machado de batalha',
    nameEn: 'Battleaxe',
    category: 'martial',
    type: 'melee',
    properties: ['versatile'],
    versatileDie: 10,
    damageDie: { count: 1, sides: 8 },
    damageType: 'Cortante',
  },
  {
    id: 'flail',
    namePt: 'Mangual',
    nameEn: 'Flail',
    category: 'martial',
    type: 'melee',
    properties: [],
    damageDie: { count: 1, sides: 8 },
    damageType: 'Concussão',
  },
  {
    id: 'glaive',
    namePt: 'Glaive',
    nameEn: 'Glaive',
    category: 'martial',
    type: 'melee',
    properties: ['heavy', 'reach', 'two-handed'],
    damageDie: { count: 1, sides: 10 },
    damageType: 'Cortante',
  },
  {
    id: 'greataxe',
    namePt: 'Machado grande',
    nameEn: 'Greataxe',
    category: 'martial',
    type: 'melee',
    properties: ['heavy', 'two-handed'],
    damageDie: { count: 1, sides: 12 },
    damageType: 'Cortante',
  },
  {
    id: 'greatsword',
    namePt: 'Espada grande',
    nameEn: 'Greatsword',
    category: 'martial',
    type: 'melee',
    properties: ['heavy', 'two-handed'],
    damageDie: { count: 2, sides: 6 },
    damageType: 'Cortante',
  },
  {
    id: 'halberd',
    namePt: 'Alabarda',
    nameEn: 'Halberd',
    category: 'martial',
    type: 'melee',
    properties: ['heavy', 'reach', 'two-handed'],
    damageDie: { count: 1, sides: 10 },
    damageType: 'Cortante',
  },
  {
    id: 'lance',
    namePt: 'Lança de montaria',
    nameEn: 'Lance',
    category: 'martial',
    type: 'melee',
    properties: ['reach', 'special'],
    damageDie: { count: 1, sides: 12 },
    damageType: 'Perfurante',
  },
  {
    id: 'longsword',
    namePt: 'Espada longa',
    nameEn: 'Longsword',
    category: 'martial',
    type: 'melee',
    properties: ['versatile'],
    versatileDie: 10,
    damageDie: { count: 1, sides: 8 },
    damageType: 'Cortante',
  },
  {
    id: 'maul',
    namePt: 'Malho',
    nameEn: 'Maul',
    category: 'martial',
    type: 'melee',
    properties: ['heavy', 'two-handed'],
    damageDie: { count: 2, sides: 6 },
    damageType: 'Concussão',
  },
  {
    id: 'morningstar',
    namePt: 'Estrela da manhã',
    nameEn: 'Morningstar',
    category: 'martial',
    type: 'melee',
    properties: [],
    damageDie: { count: 1, sides: 8 },
    damageType: 'Perfurante',
  },
  {
    id: 'pike',
    namePt: 'Pique',
    nameEn: 'Pike',
    category: 'martial',
    type: 'melee',
    properties: ['heavy', 'reach', 'two-handed'],
    damageDie: { count: 1, sides: 10 },
    damageType: 'Perfurante',
  },
  {
    id: 'rapier',
    namePt: 'Rapieira',
    nameEn: 'Rapier',
    category: 'martial',
    type: 'melee',
    properties: ['finesse'],
    damageDie: { count: 1, sides: 8 },
    damageType: 'Perfurante',
  },
  {
    id: 'scimitar',
    namePt: 'Cimitarra',
    nameEn: 'Scimitar',
    category: 'martial',
    type: 'melee',
    properties: ['finesse', 'light'],
    damageDie: { count: 1, sides: 6 },
    damageType: 'Cortante',
  },
  {
    id: 'shortsword',
    namePt: 'Espada curta',
    nameEn: 'Shortsword',
    category: 'martial',
    type: 'melee',
    properties: ['finesse', 'light'],
    damageDie: { count: 1, sides: 6 },
    damageType: 'Perfurante',
  },
  {
    id: 'trident',
    namePt: 'Tridente',
    nameEn: 'Trident',
    category: 'martial',
    type: 'melee',
    properties: ['thrown', 'versatile'],
    versatileDie: 8,
    damageDie: { count: 1, sides: 6 },
    damageType: 'Perfurante',
    rangeNormal: 6,
    rangeLong: 18,
  },
  {
    id: 'war-pick',
    namePt: 'Picareta de guerra',
    nameEn: 'War pick',
    category: 'martial',
    type: 'melee',
    properties: [],
    damageDie: { count: 1, sides: 8 },
    damageType: 'Perfurante',
  },
  {
    id: 'warhammer',
    namePt: 'Martelo de guerra',
    nameEn: 'Warhammer',
    category: 'martial',
    type: 'melee',
    properties: ['versatile'],
    versatileDie: 10,
    damageDie: { count: 1, sides: 8 },
    damageType: 'Concussão',
  },
  {
    id: 'whip',
    namePt: 'Chicote',
    nameEn: 'Whip',
    category: 'martial',
    type: 'melee',
    properties: ['finesse', 'reach'],
    damageDie: { count: 1, sides: 4 },
    damageType: 'Cortante',
  },

  // --- Armas marciais à distância (5) ---------------------------------------
  {
    id: 'blowgun',
    namePt: 'Zarabatana',
    nameEn: 'Blowgun',
    category: 'martial',
    type: 'ranged',
    properties: ['ammunition', 'loading'],
    damageDie: { count: 0, sides: 0 },
    damageType: 'Perfurante',
    damageBonus: 1,
    // 25/100 pés = 7,5/30 m: o normal é fracionário e o editor arredonda ao gravar.
    rangeNormal: 7.5,
    rangeLong: 30,
    ammoType: 'Agulha de zarabatana',
  },
  {
    id: 'hand-crossbow',
    namePt: 'Besta de mão',
    nameEn: 'Hand crossbow',
    category: 'martial',
    type: 'ranged',
    properties: ['ammunition', 'light', 'loading'],
    damageDie: { count: 1, sides: 6 },
    damageType: 'Perfurante',
    rangeNormal: 9,
    rangeLong: 36,
    ammoType: 'Virote',
  },
  {
    id: 'heavy-crossbow',
    namePt: 'Besta pesada',
    nameEn: 'Heavy crossbow',
    category: 'martial',
    type: 'ranged',
    properties: ['ammunition', 'heavy', 'loading', 'two-handed'],
    damageDie: { count: 1, sides: 10 },
    damageType: 'Perfurante',
    rangeNormal: 30,
    rangeLong: 120,
    ammoType: 'Virote',
  },
  {
    id: 'longbow',
    namePt: 'Arco longo',
    nameEn: 'Longbow',
    category: 'martial',
    type: 'ranged',
    properties: ['ammunition', 'heavy', 'two-handed'],
    damageDie: { count: 1, sides: 8 },
    damageType: 'Perfurante',
    rangeNormal: 45,
    rangeLong: 180,
    ammoType: 'Flecha',
  },
  {
    id: 'net',
    namePt: 'Rede',
    nameEn: 'Net',
    category: 'martial',
    type: 'ranged',
    properties: ['special', 'thrown'],
    damageDie: { count: 0, sides: 0 },
    damageType: 'Concussão',
    // 5/15 pés = 1,5/4,5 m: ambos fracionários; o editor arredonda ao gravar.
    rangeNormal: 1.5,
    rangeLong: 4.5,
  },
];
